google/oboe

include/oboe/AudioStream.h
include/oboe/AudioStreamBuilder.h
include/oboe/Utilities.h
src/aaudio/AudioStreamAAudio.cpp
src/aaudio/AudioStreamAAudio.h
src/common/AudioStreamBuilder.cpp
src/common/Utilities.cpp
src/opensles/AudioStreamOpenSLES.h

Use this for deciding whether to support AAudio.

oboe: add general purpose getSdkVersion() query

---

include/oboe/AudioStream.h
src/aaudio/AudioStreamAAudio.h

This is just for debugging and testing.

oboe: add debug method for getting AAudioStream

---

src/common/AudioStreamBuilder.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.cpp

Use runtime query getSdkVersion() for OpenSL ES

---

include/oboe/AudioStream.h
src/aaudio/AudioStreamAAudio.cpp
src/aaudio/AudioStreamAAudio.h

Based on getTimestamp().
Fixes #69

oboe: add calculateLatencyMillis()

---

include/oboe/AudioStreamBuilder.h
src/opensles/AudioStreamOpenSLES.cpp

Set deviceId to kUnspecified for OpenSL ES.

---

include/oboe/AudioStreamBuilder.h

Address comment left from other pull request.

oboe: change "subsequent" to "created"

---

README.md

Do not merge as is, waiting on a number of confirmations

Add links to projects using Oboe

---

src/common/Utilities.cpp

this is for https://github.com/google/oboe/issues/118
works Android-17 and Android-P.

Add debug function convertToText<AuduiStream*>(AudioStream* )

---

include/oboe/ResultWithValue.h
src/common/Utilities.cpp

simply overload << to ease debug functions, please take a look. Thanks!

Adding operator overloading for ResultWithValue<T>

---

src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/OpenSLESUtilities.cpp
src/opensles/OpenSLESUtilities.h

opensles: fix API level check for FLOAT

---

src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioInputStreamOpenSLES.h
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.h
src/opensles/AudioStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.h
tests/CMakeLists.txt
tests/testStreamClosedMethods.cpp
tests/testStreamStates.cpp

Adding tests and states for OpenSL ES input and output streams.

Implement stream states for OpenSL ES streams

---

include/oboe/Definitions.h

This will allow Oboe to compile with old NDKs.

oboe: remove dependencies on P constants

---

CMakeLists.txt
samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
samples/MegaDrone/src/main/cpp/Oscillator.h
samples/MegaDrone/src/main/cpp/Synth.h
samples/RhythmGame/src/main/cpp/audio/SoundRecording.cpp
samples/RhythmGame/src/main/cpp/utils/LockFreeQueue.h
samples/RhythmGame/src/main/cpp/utils/UtilityFunctions.h
samples/hello-oboe/src/main/cpp/PlayAudioEngine.cpp
samples/hello-oboe/src/main/cpp/SineGenerator.cpp
samples/hello-oboe/src/main/cpp/jni_bridge.cpp
src/aaudio/AAudioLoader.cpp
src/aaudio/AudioStreamAAudio.cpp
src/common/Utilities.cpp
src/fifo/FifoBuffer.cpp
src/fifo/FifoControllerBase.cpp
src/fifo/FifoControllerIndirect.cpp
src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioStreamBuffered.cpp
src/opensles/AudioStreamOpenSLES.cpp

this should get rid of issue https://github.com/google/oboe/issues/169. PTAL

Convert c-type cast to C++ cast

---

CMakeLists.txt
samples/LiveEffect/src/main/cpp/CMakeLists.txt
samples/MegaDrone/CMakeLists.txt
samples/RhythmGame/CMakeLists.txt
samples/debug-utils/logging_macros.h
samples/hello-oboe/CMakeLists.txt

re-open this one as I deleted the branch  for https://github.com/google/oboe/pull/164 accidently

Adding -Ofast for sample build.

---

src/aaudio/AudioStreamAAudio.cpp
tests/CMakeLists.txt
tests/README
tests/testStreamClosedMethods.cpp
tests/testStreamStates.cpp
tests/testXRunBehaviour.cpp

Avoid state transition problems in O and O_MR1.
Bug: #65

aaudio: don't pause if already paused

---

src/common/AudioStreamBuilder.cpp

Can be used to disable AAudio API for testing of OpenSL ES.

builder: add OBOE_ENABLE_AAUDIO preprocessor flag

---

docs/FullGuide.md

Copied from [AAudio docs](https://developer.android.com/ndk/reference/group/audio#group___audio_1gad88ad53a723807879ba75d3b5e07c073) with some minor amendments

Guidance on what you can do inside the audio callback

---

src/fifo/FifoBuffer.cpp
src/fifo/FifoBuffer.h
src/fifo/FifoControllerBase.cpp
src/fifo/FifoControllerBase.h

I saw the issue https://github.com/google/oboe/issues/200 and I thought it could be a good start for my first contribution to the Oboe project :)
Please do not hesitate to tell me if you are not looking for such contributions for now!

Remove dead code in the fifo folder

---

docs/FullGuide.md

A thread is started for you by Oboe.

remove requirement to start a thread onError

---

samples/RhythmGame/src/main/cpp/Game.cpp
samples/RhythmGame/src/main/cpp/Game.h
samples/RhythmGame/src/main/cpp/audio/Mixer.cpp
samples/RhythmGame/src/main/cpp/audio/Mixer.h
samples/RhythmGame/src/main/cpp/audio/Player.cpp
samples/RhythmGame/src/main/cpp/audio/Player.h

Basic conversion to few unique and shared pointers, an operation that is
not trivial for this kind of applications sharing many different
pointers.

RythmGame: using smart_ptr()s to handle Game dynamic data

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
apps/OboeTester/app/src/main/cpp/PlayRecordingCallback.cpp
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestInputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_test_input.xml
apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml

Request that the callback return DataCallbackResult::Stop.

oboetester: add checkbox that tells the callback to STOP

---

src/aaudio/AAudioLoader.h

oboe: initialize AAudioLoader functions to nullptr

---

src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioInputStreamOpenSLES.h
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.h

setPlayState_l() and setRecordState_l()

oboe_opensles: add _l to function names called under lock

---

samples/debug-utils/trace.cpp
samples/debug-utils/trace.h
samples/hello-oboe/src/main/cpp/PlayAudioEngine.cpp

Only show tracing warning once in log

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java

Was not plumbed through.
Also bump version to 1.2.02

fix display of xRunCount

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/AudioProcessorBase.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/AudioProcessorBase.h
apps/OboeTester/app/src/main/cpp/flowgraph/ClipToRange.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/ImpulseOscillator.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/ManyToMultiConverter.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/MonoToMultiConverter.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/RampLinear.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/SawtoothOscillator.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/SineOscillator.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/SinkFloat.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/SinkI16.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/SinkI24.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/SourceFloat.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/SourceI16.cpp
apps/OboeTester/app/src/main/cpp/flowgraph/SourceI24.cpp

Change Block to Buffer
Add comments and TODO
Use unique_ptr for float buffer.

Flowgraph cleanup

---

src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp

oboe_opensles: add locks to updateServiceFrameCounter()

---

apps/OboeTester/app/CMakeLists.txt
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/FullDuplexLatency.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexLatency.h
apps/OboeTester/app/src/main/cpp/FullDuplexStream.cpp
apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Uses Larsen effect and auto-correlation to measure input+output latency.
Requires a loopback adapter. (fun plug)

Add round trip latency test

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/FullDuplexLatency.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexLatency.h
apps/OboeTester/app/src/main/cpp/FullDuplexStream.cpp
apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/EchoActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TapToToneActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
apps/OboeTester/app/src/main/res/layout/activity_tap_to_tone.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Fix input capacity.
Add help messages.
Version 1.3.01

Oboetester: finish latency test

---

apps/OboeTester/app/CMakeLists.txt
apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.h
apps/OboeTester/app/src/main/cpp/FullDuplexGlitches.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexGlitches.h
apps/OboeTester/app/src/main/cpp/FullDuplexLatency.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexLatency.h
apps/OboeTester/app/src/main/cpp/FullDuplexStream.cpp
apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/EchoActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/res/layout/activity_glitches.xml
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/app/src/main/res/layout/stream_config.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Output a sine wave and then measure the input.
Look for deviations from the expected magnitude and phase, ie. glitches.

Glitch Test

---

tests/CMakeLists.txt
tests/UnitTestRunner/app/src/main/java/com/google/oboe/tests/unittestrunner/MainActivity.java

App was writing to a TextView not on UI thread.
Fixes #318

tests: fix cmake and testrunner

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/BufferSizeView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java
apps/OboeTester/app/src/main/res/layout/activity_glitches.xml
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
apps/OboeTester/app/src/main/res/layout/buffer_size_view.xml
apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml

Also use unordered_map to track streams.

OboeTester: add BufferSize fader to latency and glitch test

---

src/aaudio/AudioStreamAAudio.cpp
src/common/AudioStream.cpp
src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.h

Prevent race conditions with close() from another thread.

Lock waitForStateChange()

---

src/aaudio/AudioStreamAAudio.cpp
src/common/AudioStream.cpp
src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.h

Revert "Lock waitForStateChange()"

---

src/aaudio/AudioStreamAAudio.h

Test to see why it is failing.

oboe: trigger travis build

---

src/aaudio/AudioStreamAAudio.cpp
src/common/AudioStream.cpp
src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.h

Revert "Revert "Lock waitForStateChange()""

---

src/aaudio/AudioStreamAAudio.cpp
src/common/AudioStream.cpp
tests/testStreamClosedMethods.cpp
tests/testStreamStates.cpp

Handle timeouts better.
Coerce Starting to Started state.
Fix some tests.

Fix some issues with new waitForStateChange

---

include/oboe/Version.h

Minor API change in waitForStateChange
Numerous bug fixes

oboe: bump version to 1.2.0

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioInputTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioOutputTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/res/layout/activity_auto_glitches.xml
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Add an automated test that checks for glitches and pops when using various combinations of settings.
Results can be "shared" via GMail or Drive.

Auto Glitch

---

docs/FAQ.md

Addresses developer questions from #366

Add "Why didn't I get a low latency audio stream?"

---

apps/OboeTester/app/CMakeLists.txt
apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/MultiChannelRecording.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/cpp/util/WaveFileWriter.cpp
apps/OboeTester/app/src/main/cpp/util/WaveFileWriter.h
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RecorderActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TapToToneActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestInputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_recorder.xml
apps/OboeTester/app/src/main/res/values/strings.xml
apps/OboeTester/app/src/main/res/xml/provider_paths.xml

OboeTester: add WaveFileWriter for recorder

---

docs/FullGuide.md

Explain impact of registering an error callback.

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexEcho.h
apps/OboeTester/app/src/main/cpp/FullDuplexGlitches.h
apps/OboeTester/app/src/main/cpp/FullDuplexStream.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexStream.h
apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioOutputTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/BufferSizeView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java

Calculate SNR against reference sine wave.
Change configurations tested for AutoGlitch
Process one frame at a time in LatencyAnalyzer.
Change default BufferSize based on test.
Show peak amplitude during glitch test.

Oboetester: improve auto glitch test

---

tests/README.md

Update unit tests documentation

---

apps/OboeTester/README.md

Add Android Studio version requirement

---

samples/LiveEffect/src/main/java/com/google/sample/oboe/liveEffect/MainActivity.java
samples/MegaDrone/src/main/java/com/example/oboe/megadrone/MainActivity.java
samples/RhythmGame/src/main/java/com/google/oboe/sample/rhythmgame/MainActivity.java
samples/hello-oboe/src/main/java/com/google/sample/oboe/hellooboe/MainActivity.java

Refactoring various samples to close exclusive stream onPause() per best practice.

close exclusive streams onPause(), fix Issue 448

---

samples/hello-oboe/src/main/java/com/google/sample/oboe/hellooboe/MainActivity.java

Using constants for spinner default values

---

include/oboe/AudioStreamBuilder.h
src/common/AudioStreamBuilder.cpp

Log error if attempting to open AAudio when not recomended

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioMidiTester.java

OboeTester: load native library from service

---

docs/FullGuide.md

Adding new configurable stream parameters (API >= 28) and adding clarity to the role of existing ones.

Updating FullGuide.md to address documentation issues

---

include/oboe/AudioStream.h
src/common/AudioStream.cpp
src/common/StabilizedCallback.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.h
src/opensles/AudioStreamBuffered.cpp
src/opensles/AudioStreamBuffered.h

This CL addresses some of the simple changes suggested
in https://github.com/google/oboe/pull/352

Small non-functional changes

---

src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioInputStreamOpenSLES.h
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.h
src/opensles/AudioStreamBuffered.cpp
src/opensles/AudioStreamBuffered.h
src/opensles/AudioStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.h

Addresses comments from #352 
Adds consts to channelCountToChannelMask(), formats a few lines,
makes explicit certain casts, substitutes some types.

Cleanup opensles files

---

.ci_tools/build_samples.sh

Simple fix for https://github.com/google/oboe/issues/584

Fix github issue 584

---

include/oboe/AudioStream.h
src/aaudio/AudioStreamAAudio.cpp
src/aaudio/AudioStreamAAudio.h
src/opensles/AudioStreamOpenSLES.h

Following suggestion from #352

Make AudioStream::getState() const

---

apps/OboeTester/app/CMakeLists.txt
apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/cpp/FullDuplexLatency.h
apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/RandomPulseGenerator.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/cpp/unused/unused.h
apps/OboeTester/app/src/main/cpp/util/ManchesterEncoder.h
apps/OboeTester/app/src/main/cpp/util/RoundedManchesterEncoder.h
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestInputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
apps/OboeTester/build.gradle

This replaces the measurement based on the Larsen effect.
The pulse is a random series of bits encoded using Manchester Code.
This technique works at any volume level.

Use random pulse for latency test

---

src/aaudio/AudioStreamAAudio.cpp

aaudio: add comments about limiting input capacity

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/res/layout/activity_main.xml

Saves us having to dig though Settings.

OboeTester: show build on main screen

---

apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/BufferSizeView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/EchoActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ExponentialTaper.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml

For more details, see:
https://github.com/google/oboe/blob/master/apps/OboeTester/docs/AutomatedTesting.md

OboeTester: run latency test from intent

---

src/fifo/FifoBuffer.cpp
src/fifo/FifoBuffer.h
src/fifo/FifoController.cpp
src/fifo/FifoController.h
src/fifo/FifoControllerBase.cpp
src/fifo/FifoControllerBase.h
src/fifo/FifoControllerIndirect.cpp
src/fifo/FifoControllerIndirect.h
src/opensles/AudioStreamBuffered.cpp
src/opensles/AudioStreamBuffered.h

Improve safety of unsigned casts.
Move threshold up to AudioStreamBuffered.cpp
Check ranges in read/write.

Fifo cleanup

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexStream.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexStream.h
apps/OboeTester/app/src/main/cpp/InputStreamCallbackAnalyzer.cpp
apps/OboeTester/app/src/main/cpp/InputStreamCallbackAnalyzer.h
apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/InputMarginView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RecorderActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestInputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_echo.xml
apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml
apps/OboeTester/app/src/main/res/layout/activity_recorder.xml
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
apps/OboeTester/app/src/main/res/layout/input_margin_view.xml
include/oboe/AudioStream.h
src/common/AudioStream.cpp

This can be used to run automated glitch tests on Android.
More info here:
https://github.com/google/oboe/blob/master/apps/OboeTester/docs/AutomatedTesting.md

Use an Intent to launch a Glitch test

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java

OboeTester: fix crash on open,start,open

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
include/oboe/Version.h
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.h

Check buffer depth first.
Fixes #624

Fix start,pause,start in OpenSL ES

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/NativeEngine.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java
apps/OboeTester/app/src/main/res/layout/activity_auto_glitches.xml
apps/OboeTester/app/src/main/res/layout/stream_config.xml

OboeTester: add checkbox for MMAP mode

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/EchoActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java

OboeTester: reset configuration between activities

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/EchoActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RecorderActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivity.java
apps/OboeTester/app/src/main/res/values/strings.xml

Clean up report.
Handle failure to open a stream.

Fix auto glitch test

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java
apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml

Adjust sensitivity of Glitch Test

OboeTester: add Tolerance fader

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java
apps/OboeTester/app/src/main/res/layout/stream_config.xml
apps/OboeTester/app/src/main/res/values/strings.xml
src/opensles/AudioInputStreamOpenSLES.cpp

Also bump to code 22, name 1.5.14

OboeTester: add menu for InputPreset

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioOutputTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/BufferSizeView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java

Set size based on position when opened.
Enable during glitch test.
Show estimated size if stream reopened with same capacity.

OboeTester: improve buffer size slider

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java

For glitch test when launched using an Intent.
Fixes #664

OboeTester: add tolerance parameter

---

src/common/LatencyTuner.cpp

Double initial stream buffer size.

---

src/aaudio/AudioStreamAAudio.cpp
src/aaudio/AudioStreamAAudio.h
src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.h

oboe: log unsupported attributes, fixes #651

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java

OboeTester: show Oboe version

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Run the latency test 10 times and report the average latency.

OboeTester: add Average button for latency

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestDisconnectActivity.java
apps/OboeTester/app/src/main/res/layout/activity_auto_glitches.xml
apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
apps/OboeTester/app/src/main/res/layout/activity_test_disconnect.xml

Show status and make it more clear.

OboeTester: show disconnect instructions in red

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/NativeEngine.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java

Was causing 30 second delay in Open while
waiting for media.aaudio service.
Fixes #724

OboeTester: fix isMMapEnabled()

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml

Use ConstraintLayout for MainActivity.
Use smaller text for ManualGlitchActivity.

OboeTester: improve layouts for small screens

---

docs/GettingStarted.md

Clarify default values in GettingStarted.md

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java

Allows automated glitch testing for various input presets.
For Issue #740

OboeTester: add in_preset for automation

---

apps/OboeTester/app/src/main/cpp/AudioStreamGateway.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestDisconnectActivity.java

Clean up some native code to prevent hitting NULLs.

OboeTester: test INPUT disconnects

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
include/oboe/Version.h
src/common/FilterAudioStream.cpp
src/common/FilterAudioStream.h

pass onErrorBeforeClose calls to proxy

---

src/opensles/AudioStreamOpenSLES.cpp
tests/CMakeLists.txt
tests/testStreamOpen.cpp

honor setFramesPerCallback()

---

samples/drumthumper/src/main/java/com/google/oboe/sample/drumthumper/DrumThumperActivity.kt

Fix erroneous restart on initial device list notification

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java

It was getting cut off on devices with small screens.

OboeTester: move average latency report up

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java

For debugging race condition related to load.

OboeTester: show % CPU load

---

samples/drumthumper/src/main/cpp/DrumPlayerJNI.cpp
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp

[DrumThumper] Fix audio stream not starting on OpenSL

---

samples/drumthumper/src/main/cpp/DrumPlayerJNI.cpp
samples/drumthumper/src/main/java/com/google/oboe/sample/drumthumper/DrumPlayer.kt
samples/drumthumper/src/main/java/com/google/oboe/sample/drumthumper/DrumThumperActivity.kt
samples/gradle/wrapper/gradle-wrapper.properties
samples/iolib/src/main/cpp/player/DataSource.h
samples/iolib/src/main/cpp/player/OneShotSampleSource.cpp
samples/iolib/src/main/cpp/player/OneShotSampleSource.h
samples/iolib/src/main/cpp/player/SampleBuffer.cpp
samples/iolib/src/main/cpp/player/SampleSource.h
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.h
samples/parselib/src/main/cpp/io/stream/MemInputStream.h

Gentlemen,
Please take a look. I plan to do some more documentation, but I think the logic is good.

Implemented stereo playback in DrumThumper.

---

apps/fxlab/app/src/main/cpp/DuplexCallback.h

Change callback to support arbitrary channel counts.

---

samples/drumthumper/README.md
samples/iolib/README.md
samples/parselib/README.md

https://github.com/google/oboe/issues/801

Initial addition of README.md file for DrumThumper Sample.

---

docs/GettingStarted.md

Simply made the getting started info more clear.
Fixed a simple formatting issue.

Update prefab usage instructions

---

CMakeLists.txt
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
include/oboe/AudioStream.h
include/oboe/Version.h
src/aaudio/AudioStreamAAudio.cpp
src/common/AudioStream.cpp
src/common/AudioStreamBuilder.cpp
src/common/DataConversionFlowGraph.cpp
src/common/OboeDebug.h
src/fifo/FifoBuffer.cpp
src/opensles/AudioInputStreamOpenSLES.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp
src/opensles/AudioStreamOpenSLES.cpp

Enable LOGI and error logs in release builds.

---

apps/OboeTester/app/src/main/res/layout/activity_main.xml

Makes more room for other buttons.

OboeTester: use 2 columns on main screen

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java

OboeTester: fix leak of IntentReceiver

---

build_all_android.sh
prefab/oboe-VERSION.pom
prefab/oboe-VERSION/prefab/prefab.json
prefab_build.sh

Packaging and changing all the prefab config files was taking a long time so I've created a script to do it. Should save quite a bit of time for future releases.

Add script to create prefab package and maven artifact

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.h

Fix crash on OboeTester for Android < 8

---

apps/OboeTester/app/src/main/java/com/google/sample/audio_device/AudioDeviceInfoConverter.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java

Based on device ID.
Related to #874

OboeTester: start SCO when needed

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/WorkloadView.java

OboeTester: reset workload

---

tests/CMakeLists.txt
tests/run_tests.sh
tests/testAAudio.cpp
tests/testFlowgraph.cpp
tests/testStreamClosedMethods.cpp
tests/testStreamOpen.cpp
tests/testXRunBehaviour.cpp

unit tests: added direct AAudio test

---

samples/drumthumper/src/main/AndroidManifest.xml
samples/drumthumper/src/main/cpp/DrumPlayerJNI.cpp
samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/DrumPlayer.kt
samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/DrumThumperActivity.kt
samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/TriggerPad.kt
samples/drumthumper/src/main/res/layout-land/drumthumper_activity.xml
samples/drumthumper/src/main/res/layout/drumthumper_activity.xml

Changed app namespace to com.plausiblesoftware.

Initial prep for Playstore.

---

samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
samples/hello-oboe/src/main/cpp/HelloOboeEngine.h
samples/hello-oboe/src/main/cpp/LatencyTuningCallback.cpp
samples/hello-oboe/src/main/cpp/LatencyTuningCallback.h
samples/shared/DefaultAudioStreamCallback.h

Save properties so the user selections are honored.
Use shared stream.
Use locks to prevent race conditions and crashes.
See #879

hello-oboe: store properties, refactor native code

---

README.md

I was also testing GitHub access.

README - mention workarounds

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestInputActivity.java

Message now says unimplemented.
Fixes #785

OboeTester: pause on TEST INPUT not an error

---

apps/OboeTester/app/CMakeLists.txt
apps/OboeTester/app/src/main/cpp/AudioStreamGateway.h
apps/OboeTester/app/src/main/cpp/InputStreamCallbackAnalyzer.cpp
apps/OboeTester/app/src/main/cpp/InputStreamCallbackAnalyzer.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/OboeTesterStreamCallback.cpp
apps/OboeTester/app/src/main/cpp/OboeTesterStreamCallback.h

For input and output stream callback threads.

OboeTester: print scheduler when it changes

---

apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/analyzer/ManchesterEncoder.h
apps/OboeTester/app/src/main/cpp/analyzer/PeakDetector.h
apps/OboeTester/app/src/main/cpp/analyzer/PseudoRandom.h
apps/OboeTester/app/src/main/cpp/analyzer/RandomPulseGenerator.h
apps/OboeTester/app/src/main/cpp/analyzer/RoundedManchesterEncoder.h

Android CTS Verifier copied the code from analyzer
into Android. Now that Oboe is in /external/oboe we
can use the code in Oboe directly.

OboeTester: backport analyzer from CTS Verifier

---

NOTICE

Android: add files needed by AOSP for external repos

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml

When taking an average round-trip latency measurement,
retry if it fails occasionally.

OboeTester: support BT latency measurement

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp

Needed to reset the graph on start.
Fixes #1014

OboeTester: fix tap-to-tone

---

apps/OboeTester/app/src/main/res/layout/activity_echo.xml

Had to put the echo test layout inside a `ScrollView` as it was too high to fit on a single screen.

[OboeTester] Put echo test layout inside ScrollView

---

include/oboe/AudioStreamBase.h
src/common/AudioStreamBuilder.cpp

Add parameter validation to AudioStreamBase

---

samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
samples/MegaDrone/src/main/cpp/MegaDroneEngine.cpp
samples/MegaDrone/src/main/cpp/MegaDroneEngine.h
samples/RhythmGame/src/main/cpp/Game.cpp
samples/RhythmGame/src/main/cpp/Game.h
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.h

This is for github issue https://github.com/google/oboe/issues/830, please kindly take a look, thank you!

Convert samples to use shared_ptr stream creation interface

---

samples/drumthumper/README.md
samples/iolib/src/main/cpp/player/SampleBuffer.cpp

for adding support for Stereo input samples (though not the
implementation).
Issue #801

Updated README.md to relect current behavior and have instructions

---

samples/drumthumper/build.gradle
samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/DrumPlayer.kt
samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/DrumThumperActivity.kt
samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/TriggerPad.kt

Applying code improvements suggested by Android Studio
- Use of property access syntax instead of setter method;
- Make some methods private;
- Convert concatenation to template ;
- Removed unused variables and parameters;
- Updated the libraries `androidx.appcompat:appcompat` and `androidx.core:core-ktx` to the last versions.
Successfully tested on Android Studio 4.0.1

[Drumthumper] Code improvements

---

apps/OboeTester/build.gradle

This would fix CI failures in PR #1036, PTAL.

Make google maven before jcenter for OboeTester

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestDisconnectActivity.java

Must be ERROR_DISCONNECTED to pass.
See b/170551030

OboeTester: check for errorCallback error code

---

src/flowgraph/FlowGraphNode.h

Define a virtual destructor for base class.

Add virtual destructor to FlowGraphPort.

---

samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/TriggerPad.kt

Allows a pad to be played while it is still pressed.
This allows the user to touch the same piece quickly without worrying about pressing and lifting the finger quickly.

[Drumthumper] Allows a pad to be played while it is still pressed

---

src/aaudio/AudioStreamAAudio.cpp
src/opensles/AudioInputStreamOpenSLES.cpp

oboe: change VoicePerformance to VoiceRecognition on P

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/google/sample/audio_device/AudioDeviceInfoConverter.java
apps/OboeTester/app/src/main/java/com/google/sample/audio_device/AudioDeviceListEntry.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/DeviceReportActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MicrophoneInfoConverter.java
apps/OboeTester/app/src/main/res/layout/activity_device_report.xml
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/app/src/main/res/values/strings.xml

OboeTester: add device report and mic info

---

tests/testStreamWaitState.cpp

Seems broken on OpenSL ES.
Tests for #1061

tests: test waitForStateChange() timeout

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp
apps/OboeTester/app/src/main/cpp/SawPingGenerator.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioMidiTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioOutputTester.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioOutputStream.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TapToToneActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java

Remove unused setToneType().
Change setEnabled(b) to trigger().

OboeTester: refactor trigger of ping

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/DeviceReportActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MicrophoneInfoConverter.java
apps/OboeTester/app/src/main/res/layout/activity_device_report.xml
apps/OboeTester/app/src/main/res/layout/audio_devices.xml
apps/OboeTester/app/src/main/res/values/strings.xml

MinSPL, Sensitivity, etc
Also ProAudio Feature, etc.

OboeTester: more mic info and properties

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/DeviceReportActivity.java

Failed on P or earlier Android

OboeTester: fix microphone report

---

src/aaudio/AudioStreamAAudio.cpp
src/common/LatencyTuner.cpp
src/opensles/OpenSLESUtilities.cpp

Simplify AudioStreamAAudio constructor.
Add comment about setBufferSize in LatencyTuner.
Use SL constants for switch statement.
See #352

oboe: fix some misc issue for Chrome

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java

Add channels, sample rate, perf mode, sharing mode.
Fixes #1071

OboeTester: add more parameters to auto-latency test

---

docs/AndroidAudioHistory.md

Document regression in headset plugin handling.

Add RQ1A disconnect bug to AndroidAudioHistory.md

---

src/aaudio/AudioStreamAAudio.cpp

Coerce the ErrorTimeout to ErrorDisconnected if R.
This is to fix b/173928197
This can prevent apps that were looking specifically for the
ErrorDisconnected from failing to restart their streams.

oboe: workaround disconnect bug in RQ1A

---

samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp

It was turning off if the buffer size was changed.

hello-oboe: fix latency supported logic

---

apps/fxlab/build.gradle
apps/fxlab/gradle/wrapper/gradle-wrapper.properties

Fixes broken build:
https://issuetracker.google.com/issues/175895275

fxlab: update gradle

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TapLatencyAnalyser.java

OboeTester: clean up TapLatencyAnalyzer

---

src/aaudio/AAudioLoader.cpp

Do not call dlclose on AAudio.
It could cause a segfault if thread_local was used by AAudio.
And the destructor is never called anyway so there is no resource leak.
Fixes #1160

oboe: remove call to dlclose()

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/BufferSizeView.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java
apps/OboeTester/app/src/main/res/layout/buffer_size_view.xml

Add radio buttons for setting buffer size
to 1,2 or 3 bursts.
We still support the fader for intermediate sizes.

OboeTester: allow set size by burst

---

apps/fxlab/app/src/main/java/com/mobileer/androidfxlab/MainActivity.kt

Move engine/ui startup/shutdown to app create/destroy

---

samples/LiveEffect/src/main/cpp/FullDuplexPass.h

Issue: https://github.com/google/oboe/issues/1176

fixed name of variable used to calculate numOutputSamples

---

apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml
apps/OboeTester/app/src/main/res/xml/button_color_selector.xml

- Add LEANBACK_LAUNCHER category so app shows up in TV launcher.
- Fix stream control button focus highlight so that you can tell which
button has focus when navigating using a TV remote.

Slight improvement for Android TV support

---

samples/parselib/src/main/cpp/wav/WavStreamReader.cpp
samples/parselib/src/main/cpp/wav/WavStreamReader.h

Fixed (potential) memory leak in WavStreamReader

---

samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
samples/hello-oboe/src/main/cpp/HelloOboeEngine.h
samples/hello-oboe/src/main/cpp/jni_bridge.cpp
samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/MainActivity.java
samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/PlaybackEngine.java

Prevent stream from being opened multiple times when the app is started.
The menu updates were triggering reopen().
Show Toast with error message if open or start fails.
For #1239

HelloOboe: only open stream once when launched

---

samples/RhythmGame/src/main/cpp/Game.cpp
samples/RhythmGame/src/main/cpp/Game.h
samples/shared/Mixer.h

[RhythmGame] Add headphone connect handling

---

apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioQueryTools.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/BaseAutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/DeviceReportActivity.java
apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestDataPathsActivity.java
apps/OboeTester/app/src/main/res/values/strings.xml

For example, Pro Audio features, chip names.
This will help us develop Quirks for specific devices.
Change test name from "Report Devices" to "Device Report".
Change channel text.

OboeTester: add more device info to reports

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
apps/OboeTester/app/src/main/res/layout/stream_config.xml
apps/OboeTester/app/src/main/res/values/strings.xml

New option in output configuration.

OboeTester: add Usage menu

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java
apps/OboeTester/app/src/main/res/layout/activity_tap_to_tone.xml
apps/OboeTester/app/src/main/res/layout/merge_audio_simple.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Tell user to press start and to tap on green box.
#Fixes 1303

OboeTester: better tap-to-tone instructions

---

samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp

[LiveEffect] Add format conversion for devices running API 20 or below

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExternalTapToToneActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneTester.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/WaveformView.java
apps/OboeTester/app/src/main/res/values/strings.xml

The external tap-to-tone was not asking for record permission.
So it might crash.
Fixes #1337

OboeTester: fix record permissions for tap test

---

src/common/QuirksManager.cpp

This switches off MMAP when the following conditions are met: 
- Stream direction is INPUT
- Device has Exynos 9810 CPU
- Build changelist is 18847185 or earlier (corresponds to incremental build G965FXXSBETH2)
- Input preset is NOT `VoiceCommunication`
In order to add this quirk I have used the changelist 18847185 which was obtained from this source:
https://www.sammobile.com/samsung/galaxy-s9-plus/firmware/SM-G965F/DBT/download/G965FXXSBETH2/364838/

Add quirk for S9 recording silence sometimes. Fixes #1110

---

.github/workflows/android.yml

build: run CI tests on main branch

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/res/layout/activity_main.xml

Apply UI settings when the stream is opened.
Prevent mismatch between apparent stream settings and actual settings.
Bump OboeTester version to 2.1.2
Fixes #921

OboeTester: honor menus

---

tests/testStreamOpen.cpp

Fixes #1344
It seems like if we set PackageName to something weird, we won't be able to get mic permissions. Added some tests for a sanity check

Add input SetPackageName/SetAttributionTag tests

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

Also the Auto GLitches report.
Compare failed test with closest test that passed.
This will highlight the parameter that is specific to the failure.
Fixes #1367

OboeTester: improve readability of DATA PATHS report

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/VolumeBarView.java

Use log() to display volume in dB.
This will make it easier to evaluate silent or low level signals.

OboeTester: improve VU meter display

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneTester.java

Disable/enable the waveform view based on running status.
Fixes #1370

OboeTester: prevent taps when stopped

---

apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneTester.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/WaveformView.java

Also display glitch waveform better.
Fixes #512

OboeTester: suggest raising volume

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java

(OboeTester) Add time when tap to tone is pressed to logs

---

samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp

Fixes #1070
This change helps simplify our samples

(HelloOboe) Use CalculateLatencyMillis

---

apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml
apps/OboeTester/app/src/main/res/layout/auto_test_runner.xml

Fixes #870 
This page is getting large and unwieldy. Consider cleaning up unnecessary data in another PR.

(OboeTester) Add sine amplitude to glitch test

---

include/oboe/AudioStreamBuilder.h

Add more info for setFramesPerDataCallback

---

samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/DrumPlayer.kt
samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/DrumThumperActivity.kt
samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/TriggerPad.kt

(drumthumper) remove redundant semicolon in kotlin

(drumthumper) remove redundant semicolon in kotlin

---

src/flowgraph/FlowGraphNode.h
src/flowgraph/MonoToMultiConverter.cpp
src/flowgraph/MonoToMultiConverter.h

Fix 1407 sync flowgraph

---

src/flowgraph/ChannelCountConverter.cpp
src/flowgraph/FlowGraphNode.h
src/flowgraph/MultiToMonoConverter.cpp
src/flowgraph/SampleRateConverter.cpp
src/flowgraph/SinkFloat.cpp
src/flowgraph/resampler/PolyphaseResampler.cpp
src/flowgraph/resampler/README.md
src/flowgraph/resampler/SincResampler.cpp

Sync flowgraph with internal repo

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioStreamBase.java

So we can see numeric wraparound easier.

OboeTester: show frames in hex

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
prefab/oboe-VERSION/AndroidManifest.xml
samples/LiveEffect/build.gradle
samples/LiveEffect/src/main/AndroidManifest.xml
samples/MegaDrone/build.gradle
samples/MegaDrone/src/main/AndroidManifest.xml
samples/RhythmGame/build.gradle
samples/RhythmGame/src/main/AndroidManifest.xml
samples/SoundBoard/build.gradle
samples/SoundBoard/src/main/AndroidManifest.xml
samples/audio-device/build.gradle
samples/drumthumper/build.gradle
samples/drumthumper/src/main/AndroidManifest.xml
samples/hello-oboe/build.gradle
samples/hello-oboe/src/main/AndroidManifest.xml
samples/iolib/build.gradle
samples/parselib/build.gradle

Bump minSdkVersion to 21 and targetSdkVersion to 31

---

.github/workflows/android.yml
samples/audio-device/build.gradle
samples/build.gradle
samples/gradle/wrapper/gradle-wrapper.properties
samples/iolib/build.gradle
samples/parselib/build.gradle

Also remove versionCodes from libraries.
AndroidStudio made these changes when upgrading.
Related to #1483

Update gradle in samples

---

samples/README.md
samples/RhythmGame/src/main/res/layout/activity_main.xml

This PR clarifies rhythm game to be less confusing.
Fixes #1504

RhythmGame: Add some instructions

---

include/oboe/AudioStreamBuilder.h

The device is not guaranteed.
See #1472

docs: clarify setDeviceId() behavior

---

tests/UnitTestRunner/app/src/main/java/com/google/oboe/tests/unittestrunner/MainActivity.java

tests: keep screen on during unit tests

---

samples/drumthumper/build.gradle

This was on the master branch by mistake.

Update release code and app version for PlayStore update.

---

samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/MainActivity.java

startBluetoothSco is deprecated in Android T. Instead, we should use setCommunicationDevice.
This PR also cleans up a couple of other warnings from the compiler.
I will update https://github.com/google/oboe/wiki/TechNote_BluetoothAudio after this PR is submitted.

HelloOboe: Use setCommunicationDevice instead of startBluetoothSco

---

samples/LiveEffect/src/main/java/com/google/oboe/samples/liveEffect/MainActivity.java
samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
samples/hello-oboe/src/main/cpp/HelloOboeEngine.h
samples/hello-oboe/src/main/cpp/jni_bridge.cpp
samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/MainActivity.java
samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/PlaybackEngine.java

Fixes #1102
Tested on Nexus 6 with Android API 22.

HelloOboe: Disable playback device spinners on OpenSL ES

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java

OboeTester: Update Test Output channel box and signal UI

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java

Before change:
```
Device Report:
OboeTester (59) v 2.3.0, Oboe v 1.6.2Google, Pixel 4a (5G), bramble
==== Device ==================== 2
Id : 2
```
After change:
```
Device Report:
App: OboeTester (59) v 2.3.0, Oboe v 1.6.2
Phone: Google, Pixel 4a (5G), bramble
==== Device ==================== 2
Id : 2
```

OboeTester: Add extra newlines in device report for legibility

---

tests/UnitTestRunner/.gitignore
tests/UnitTestRunner/app/src/main/.gitignore

I messed up the test .gitignore in #1580. Fixing here.

Tests: Fix test gitignore

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java

OboeTester: make some native methods private

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDisconnectActivity.java

OboeTester: Fix test disconnect single test so only one test runs

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/docs/AutomatedTesting.md

OboeTester: Add duration and reports for input and output tests

---

apps/OboeTester/app/CMakeLists.txt
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/cpp/TestErrorCallback.cpp
apps/OboeTester/app/src/main/cpp/TestErrorCallback.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExtraTestsActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestErrorCallbackActivity.java
apps/OboeTester/app/src/main/res/layout/activity_error_callback.xml
apps/OboeTester/app/src/main/res/layout/activity_extra_tests.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Delete an error callback while it is being used by Oboe.
Try to reproduce issue #1603

OboeTester: add error callback test

---

apps/OboeTester/app/build.gradle
prefab/oboe-VERSION/AndroidManifest.xml
samples/LiveEffect/build.gradle
samples/MegaDrone/build.gradle
samples/RhythmGame/build.gradle
samples/SoundBoard/build.gradle
samples/audio-device/build.gradle
samples/drumthumper/build.gradle
samples/hello-oboe/build.gradle
samples/iolib/build.gradle
samples/parselib/build.gradle

Update Oboe to use API Version 33

---

CONTRIBUTING

CONTRIBUTING.md already exists so this file is not needed. See https://github.com/google/new-project

Delete extra CONTRIBUTING file

---

include/oboe/Definitions.h

Docs: Update Definitions.h to have all or no values

---

apps/OboeTester/app/local.properties

local.properties should not be checked into git. See https://github.com/google/oboe/blob/main/apps/OboeTester/.gitignore

OboeTester: Delete local.properties from git

---

docs/FullGuide.md
samples/MegaDrone/src/main/cpp/MegaDroneEngine.cpp
samples/MegaDrone/src/main/cpp/MegaDroneEngine.h
samples/SoundBoard/src/main/cpp/SoundBoardEngine.cpp
samples/SoundBoard/src/main/cpp/SoundBoardEngine.h
samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
samples/hello-oboe/src/main/cpp/HelloOboeEngine.h

Updating samples and docs to match #1626

Update samples to use shared_ptr for setErrorCallback

---

samples/MegaDrone/src/main/cpp/MegaDroneEngine.cpp
samples/MegaDrone/src/main/cpp/MegaDroneEngine.h
samples/SoundBoard/src/main/cpp/SoundBoardEngine.cpp
samples/SoundBoard/src/main/cpp/SoundBoardEngine.h

SoundBoard/MegaDrone: Retry open if it fails

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/EchoActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RecorderActivity.java

Was crashing if 13 channels selected.

OboeTester: catch IOExceptions

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/java/com/mobileer/audio_device/CommunicationDeviceSpinner.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/CommunicationDeviceView.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/EchoActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_echo.xml
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/app/src/main/res/layout/activity_test_input.xml
apps/OboeTester/app/src/main/res/layout/activity_test_output.xml
apps/OboeTester/app/src/main/res/layout/comm_device_view.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Also move setSpeakerphoneOn into test activities.

Add setCommunicationsDevice menu

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

Tune the Data Paths test.
Fixes #1672

OboeTester: fix phase error calculation

---

apps/OboeTester/app/build.gradle

OboeTester bump version to 2.3.5

---

CMakeLists.txt
src/common/DataConversionFlowGraph.cpp
src/flowgraph/Limiter.cpp
src/flowgraph/Limiter.h
src/flowgraph/resampler/SincResampler.cpp
src/flowgraph/resampler/SincResamplerStereo.cpp
tests/testFlowgraph.cpp
tests/testResampler.cpp

Add limiter to Oboe to sync between Github and AAudio flowgraph code
Fixes #1679

Flowgraph: Add Limiter

---

include/oboe/AudioStreamBuilder.h

Deprecate AudioStreamBuilder.setCallback

---

apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceInfoConverter.java

Fix internal b/265477251 - Device has "unknown" choice

Add new audio device types

---

apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h

Helps solve a build error in aosp/2441525

Comment out unused channelCount parameter

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MicrophoneInfoConverter.java

OboeTester: catch null from getChannelMapping()

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioQueryTools.java

OboeTester: Add mic and output check to Device Report

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioQueryTools.java

OboeTester: Fix and add more properties in DeviceReport

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceAdapter.java
apps/OboeTester/app/src/main/java/com/mobileer/miditools/synth/SynthEngine.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AnalyzerActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioQueryTools.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseOboeTesterActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MicrophoneInfoConverter.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfiguration.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneTester.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/VolumeBarView.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/WorkloadView.java
apps/OboeTester/app/src/main/res/layout/activity_error_callback.xml
apps/OboeTester/app/src/main/res/layout/activity_extra_tests.xml
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/gradle.properties
apps/fxlab/app/src/main/kotlin/com/mobileer/androidfxlab/NativeInterface.kt
samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/MainActivity.java

OboeTester: Use AndroidX

---

src/flowgraph/resampler/PolyphaseResampler.cpp
src/flowgraph/resampler/SincResampler.cpp
src/flowgraph/resampler/SincResamplerStereo.cpp

It was accidentally removed.
Fixes #1746

Add include <algorithm>

---

samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.h

DrumThumper: Use data and error callbacks

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml
apps/OboeTester/app/src/main/res/values/strings.xml
include/oboe/AudioStream.h
src/aaudio/AAudioLoader.cpp
src/aaudio/AAudioLoader.h
src/aaudio/AudioStreamAAudio.cpp
src/aaudio/AudioStreamAAudio.h
tests/testStreamClosedMethods.cpp

Add support for AAudioStream_release

---

apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
apps/OboeTester/app/src/main/cpp/analyzer/DataPathAnalyzer.h
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

The phase error was out of range.
Also print better report summary.
Remove VoiceCommunication test because AEC wrecks it.

Fix phase calculations in Data Paths

---

tests/testStreamClosedMethods.cpp

Unit Test: Fix flaky setDelayBeforeClosed test 

---

src/aaudio/AudioStreamAAudio.cpp

Set performance mode as None if session id is set

---

samples/SoundBoard/src/main/AndroidManifest.xml
samples/SoundBoard/src/main/cpp/Synth.h
samples/SoundBoard/src/main/kotlin/com/google/oboe/samples/soundboard/MainActivity.kt
samples/SoundBoard/src/main/kotlin/com/google/oboe/samples/soundboard/MusicTileView.kt
samples/shared/SynthSound.h

Soundboard: Support screen rotation

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java
apps/OboeTester/app/src/main/res/menu/menu_main.xml
apps/OboeTester/app/src/main/res/values/strings.xml

added basic action share button item to resolve issue #1766

---

include/oboe/AudioStreamBase.h
include/oboe/AudioStreamBuilder.h
include/oboe/Definitions.h
src/aaudio/AAudioLoader.cpp
src/aaudio/AAudioLoader.h
src/aaudio/AudioStreamAAudio.cpp
src/opensles/AudioStreamOpenSLES.cpp
tests/testStreamOpen.cpp

Add allowed capture policy to Oboe for Android Q+

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceSpinner.java
apps/OboeTester/app/src/main/java/com/mobileer/audio_device/CommunicationDeviceSpinner.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/FastButton.java

This reverts commit d2193bd6ef2833949663b93f550df11fb9298b60.
Quick fix for #1795

Revert "use app compat spinner and text view (#1769)"

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestPlugLatencyActivity.java

Changed "waiting for" to "waiting while".

Fix messages in TestPlugLatencyActivity.java

---

build_all_android.sh
samples/RhythmGame/test/run_tests.sh
tests/run_tests.sh

Change cmake -H to -S

---

tests/UnitTestRunner/app/src/main/java/com/google/oboe/tests/unittestrunner/MainActivity.java
tests/UnitTestRunner/app/src/main/res/values/strings.xml

UnitTestRunner: Update text after getting record permissions

---

apps/OboeTester/app/src/main/java/com/mobileer/audio_device/CommunicationDeviceSpinner.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/CommunicationDeviceView.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/EchoActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_echo.xml
apps/OboeTester/app/src/main/res/layout/activity_main.xml
apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
apps/OboeTester/app/src/main/res/layout/activity_tap_to_tone.xml
apps/OboeTester/app/src/main/res/layout/comm_device_view.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Move SCO dialog to CommDeviceView
To help debug b/282831177

OboeTester: consolidate CommDevice UI

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java

To catch bugs where the hardware is running at an unexpected rate.
Added to help debug b/284033428

OboeTester: measure and display sample rate

---

src/flowgraph/resampler/MultiChannelResampler.cpp
src/flowgraph/resampler/MultiChannelResampler.h
tests/testResampler.cpp

The sound was muffled when upsampling for no reason.
Fixes #1673
Fixes #1625

resampler: do not filter when upsampling

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestPlugLatencyActivity.java

OboeTester: Add more logs to Plug Latency Test

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioOutputTester.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioOutputStream.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_test_output.xml

OboeTester: Add Volume Fader

---

samples/drumthumper/src/main/kotlin/com/plausibleaudio/drumthumper/DrumPlayer.kt

DrumThumper: swap snare and mid tom position

---

apps/OboeTester/app/src/main/cpp/FullDuplexEcho.cpp
apps/OboeTester/app/src/main/cpp/FullDuplexEcho.h
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/res/layout/activity_echo.xml

OboeTester: Add volume bars to echo test

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/cpp/InputStreamCallbackAnalyzer.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
apps/OboeTester/app/src/main/cpp/OboeTesterStreamCallback.cpp
apps/OboeTester/app/src/main/cpp/OboeTesterStreamCallback.h
apps/OboeTester/app/src/main/cpp/OboeTools.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml
apps/OboeTester/app/src/main/res/values/strings.xml

Useful for testing recovery from hangs in a callback. Look for "Hang" menu under RELEASE button.
Fixes #1829

OboeTester: add menu to hang and glitch

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

OboeTester: Add channel masks to data path tests

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java

OboeTester: cleanup error messages in TestDisconnect

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

OboeTester: Keep data paths tests screen on

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml
apps/OboeTester/app/src/main/res/values/strings.xml

OboeTester: add flush button

---

src/aaudio/AAudioLoader.cpp

Remove prerelease check for Android U

---

tests/README

A better README already exists with README.md

Delete tests README

---

apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceInfoConverter.java

OboeTester: Add new info from AudioDeviceInfo to device report

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

OboeTester: Fix input channel masks data path tests

---

include/oboe/Definitions.h

Add comments on whether channel masks are input or output or both

---

samples/MegaDrone/src/main/java/com/google/oboe/samples/megadrone/MainActivity.java
samples/RhythmGame/src/main/java/com/google/oboe/samples/rhythmgame/MainActivity.java
samples/SoundBoard/src/main/kotlin/com/google/oboe/samples/soundboard/MainActivity.kt
samples/minimaloboe/src/main/kotlin/com/example/minimaloboe/AudioPlayer.kt

Samples: Handle activity lifecycle better

---

apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceInfoConverter.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

OboeTester: Output channel mask strings in Data Paths Test

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java

OboeTester: check for null in CPU LOAD test

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDisconnectActivity.java

OboeTester: initial plug state not detected

---

apps/OboeTester/app/CMakeLists.txt

A new TestColdStartLatency.cpp file was added.

Touch CMake so Android Studio will build

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDisconnectActivity.java

OboeTester keep screen on during DISCONNECT test

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestRouteDuringCallbackActivity.java

OboeTester keep screen on during ROUTING STRESS

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExternalTapToToneActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java

* External Tap-to-Tone
* Tap-to-Tone
* Auto Glitch

OboeTester: Keep screen on during 3 tests

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java

OboeTester: Add USB Device to Device Report

---

samples/RhythmGame/src/main/cpp/Game.cpp
samples/shared/Mixer.h

Add removeAllTracks

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_test_output.xml

OboeTester: Add checkbox for setStreamControlByAttributes

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
apps/OboeTester/app/src/main/res/layout/activity_dynamic_workload.xml
apps/OboeTester/app/src/main/res/layout/activity_test_output.xml
apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml

OboeTester: smaller text to fit on small screens

---

include/oboe/AudioStreamBuilder.h
src/common/AudioStreamBuilder.cpp

Removed deprecated function logging from all API inlined functions.

Log deprecated fix

---

apps/OboeTester/app/src/main/res/values/strings.xml

We want to have more smaller hang time options.

OboeTester: Add more hang times options

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
apps/OboeTester/app/src/main/res/layout/activity_data_paths.xml
apps/OboeTester/docs/AutomatedTesting.md

Fixes #1936
Note that these tests will be off by default.

OboeTester: Add sample rate tests to data paths test

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivityBase.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/WorkloadView.java
apps/OboeTester/app/src/main/res/layout/activity_dynamic_workload.xml
apps/OboeTester/app/src/main/res/values/strings.xml

This will make it easier to dial in a specific workload and also is more robust.

OboeTester: add workload fader, remove benchmark

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
apps/OboeTester/app/src/main/cpp/analyzer/DataPathAnalyzer.h
apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
apps/OboeTester/app/src/main/cpp/analyzer/InfiniteRecording.h
apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/WaveformView.java
apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml
src/flowgraph/resampler/MultiChannelResampler.cpp

* Track slowly changing sample rates
* Improve display of glitches, add cursor
* Add "Auto draw" checkbox
* Add "Force glitch" checkbox

Improve glitch tests

---

src/aaudio/AudioStreamAAudio.cpp
src/common/AudioStreamBuilder.cpp
src/common/DataConversionFlowGraph.cpp
src/common/Utilities.cpp
src/opensles/AudioOutputStreamOpenSLES.cpp

Add enums to some logs

---

apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
src/opensles/AudioStreamOpenSLES.cpp

Add more static_casts

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java

This PR adds MediaCodecInfo to OboeTester DeviceReport

OboeTester: Add MediaCodecInfo to DeviceReport

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

Added to Data Paths to catch b/270535408
Fixes #2001

OboeTester: test in_channels=3 and SessionId

---

tests/testReturnStop.cpp
tests/testStreamClosedMethods.cpp
tests/testStreamFramesProcessed.cpp
tests/testStreamOpen.cpp
tests/testStreamStates.cpp
tests/testStreamStop.cpp
tests/testStreamWaitState.cpp
tests/testXRunBehaviour.cpp

Unit Tests: Use shared_ptr

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MicrophoneInfoConverter.java

Prevent Linter errors in google3
Also prevent crash on API 25 emulator
For #2017

Oboetester: use TargetApi(28) for Mic Info

---

docs/FullGuide.md

Update Oboe docs

---

apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/res/values-night/styles.xml
apps/OboeTester/app/src/main/res/values-v21/styles.xml
apps/OboeTester/app/src/main/res/values/styles.xml

OboeTester had always used a light action bar until #2019. That PR changed the action bar to a dark theme. This PR changes action bars back to light.

OboeTester: Change action bar to light

---

apps/OboeTester/app/src/main/AndroidManifest.xml

OboeTester extra tests didn't set the screen orientation as portrait.

OboeTester: Set extra tests screen orientation as portrait

---

apps/OboeTester/app/src/main/cpp/TestRapidCycle.cpp
apps/OboeTester/app/src/main/cpp/TestRapidCycle.h
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestRapidCycleActivity.java
apps/OboeTester/app/src/main/res/values/strings.xml

This triggers a race condition and a deadlock.
To trigger #2059

OboeTester: return Stop from rapid cycle test

---

src/common/AudioStreamBuilder.cpp
src/opensles/AudioStreamOpenSLES.cpp
tests/CMakeLists.txt
tests/testReturnStopDeadlock.cpp

Try to reproduce the bug in #2059.

Test whether a stream stop can deadlock

---

samples/LiveEffect/src/main/AndroidManifest.xml
samples/LiveEffect/src/main/java/com/google/oboe/samples/liveEffect/DuplexStreamForegroundService.java
samples/LiveEffect/src/main/java/com/google/oboe/samples/liveEffect/MainActivity.java

LiveEffect: Add foreground service

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

Update as each test is run.
Partial fix for #2050

OboeTester: show Data Paths pass/fail tally

---

apps/OboeTester/docs/AutomatedTesting.md

Add foreground service params to AutomatedTesting.md

---

apps/OboeTester/app/CMakeLists.txt
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
apps/OboeTester/build.gradle
apps/OboeTester/gradle.properties
apps/OboeTester/gradle/wrapper/gradle-wrapper.properties

Build with 16 KB pages.
For #2041
See also b/358130477

OboeTester: Use 16 KB pages

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioQueryTools.java

Adding bluetooth and telephone features to device report

OboeTester: Add more features to device report

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseOboeTesterActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExtraTestsActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java

OboeTester: Fix foreground service permissions for tests not recording audio

---

samples/LiveEffect/src/main/java/com/google/oboe/samples/liveEffect/MainActivity.java

LiveEffect: Request permissions before starting foreground service

---

src/opensles/EngineOpenSLES.cpp

OpenSL ES: Add compile flag

---

CMakeLists.txt

Added Cmake option related to #2112.

Add cmake option OBOE_DO_NOT_DEFINE_OPENSL_ES_CONSTANTS

---

CMakeLists.txt
build_all_android.sh

Compile oboe with 16kb page sizes

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java

OboeTester: Add HW getters to data paths test

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java

Was not specifying MMAP requirement so all tests
got skipped on devices without MMAP.
Internal bug tracker: b/393194300

OboeTester: Auto Glitch test now handles MMAP properly

---

include/oboe/Definitions.h
src/aaudio/AAudioExtensions.h
src/aaudio/AAudioLoader.cpp
src/aaudio/AAudioLoader.h

Use new AAudio API to query MMAP policy.

---

samples/drumthumper/src/main/cpp/DrumPlayerJNI.cpp
samples/drumthumper/src/main/kotlin/com/plausibleaudio/drumthumper/DrumPlayer.kt
samples/drumthumper/src/main/kotlin/com/plausibleaudio/drumthumper/DrumThumperActivity.kt
samples/drumthumper/src/main/res/layout-land/drumthumper_activity.xml
samples/drumthumper/src/main/res/layout/drumthumper_activity.xml
samples/drumthumper/src/main/res/values/colors.xml
samples/iolib/src/main/cpp/player/OneShotSampleSource.cpp
samples/iolib/src/main/cpp/player/SampleSource.h
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.h

Add audio looping to drum thumper

DrumThumper: Add audio looping

---

apps/OboeTester/app/src/main/cpp/FormatConverterBox.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfiguration.java
apps/OboeTester/app/src/main/res/values/strings.xml
include/oboe/AudioStream.h
include/oboe/AudioStreamBase.h
include/oboe/AudioStreamBuilder.h
include/oboe/AudioStreamCallback.h
include/oboe/Definitions.h
src/aaudio/AAudioLoader.cpp
src/aaudio/AAudioLoader.h
src/aaudio/AudioStreamAAudio.cpp
src/aaudio/AudioStreamAAudio.h

Add offload support.

---

include/oboe/AudioStream.h

Follow up to comments in https://github.com/google/oboe/pull/2182

AudioStream: use [[maybe_unused]] instead of std::ignore

---

docs/FullGuide.md
include/oboe/AudioStream.h
include/oboe/AudioStreamBase.h
src/common/Utilities.cpp
src/opensles/OpenSLESUtilities.cpp

This is part of the fix for #2180

Add compressed formats to valid formats list.

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java

Make vendor and product ID easier to read.

OboeTester print hex 0x####

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
src/common/AdpfWrapper.cpp
src/common/StabilizedCallback.cpp
src/common/Trace.cpp
src/common/Trace.h

Use Singleton design pattern and early initialization
Add a "Workload" trace for OboeTester CPU LOAD test

Allow sharing of the Trace API for Perfetto

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTest.h
apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTestRunner.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioStreamBase.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioWorkloadTestActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioWorkloadTestRunnerActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/NativeEngine.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
apps/OboeTester/app/src/main/res/layout/activity_audio_workload_test.xml
apps/OboeTester/app/src/main/res/layout/activity_audio_workload_test_runner.xml
apps/OboeTester/app/src/main/res/layout/activity_dynamic_workload.xml
apps/OboeTester/docs/AutomatedTesting.md
include/oboe/AudioStream.h
src/aaudio/AudioStreamAAudio.h
src/common/AdpfWrapper.cpp
src/common/AdpfWrapper.h
src/common/StabilizedCallback.cpp
src/common/Trace.cpp
src/common/Trace.h

Add new ADPF APIs introduced in Android API level 36 to Oboe. When testing with the new AudioWorkload test, this works great!

AdpfWrapper: Add notifyWorkloadIncrease/Spike/Reset

---

CMakeLists.txt
apps/OboeTester/app/CMakeLists.txt
apps/fxlab/app/CMakeLists.txt
apps/fxlab/app/src/main/cpp/tests/CMakeLists.txt
docs/GettingStarted.md
samples/LiveEffect/src/main/cpp/CMakeLists.txt
samples/MegaDrone/src/main/cpp/CMakeLists.txt
samples/RhythmGame/CMakeLists.txt
samples/RhythmGame/test/CMakeLists.txt
samples/SoundBoard/src/main/cpp/CMakeLists.txt
samples/drumthumper/src/main/cpp/CMakeLists.txt
samples/hello-oboe/src/main/cpp/CMakeLists.txt
samples/iolib/src/main/cpp/CMakeLists.txt
samples/minimaloboe/src/main/cpp/CMakeLists.txt
samples/parselib/src/main/cpp/CMakeLists.txt
tests/CMakeLists.txt

Update min cmake version

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp

Drain offload stream when there is big amount of data written.

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestPlugLatencyActivity.java

OboeTester: Keep screen on during plug latency test

---

apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTestRunner.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioWorkloadTestRunnerActivity.java

Everything else in this file is atomic or locked in #2237

Remove mResultText in AudioWorkloadTestRunner.h

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioRecordThread.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneTester.java
apps/OboeTester/app/src/main/res/layout/activity_external_tap_to_tone.xml
apps/OboeTester/app/src/main/res/layout/activity_tap_to_tone.xml
apps/OboeTester/app/src/main/res/values/strings.xml

OboeTester: Add input source to tap to tone

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MultiLineChart.java
apps/OboeTester/app/src/main/res/layout/activity_dynamic_workload.xml
apps/OboeTester/app/src/main/res/values/strings.xml

OboeTester: Mark glitches in CPU load test with red

---

apps/OboeTester/app/CMakeLists.txt
apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/NoisePulseGenerator.cpp
apps/OboeTester/app/src/main/cpp/NoisePulseGenerator.h
apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp
apps/OboeTester/app/src/main/cpp/SawPingGenerator.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java
apps/OboeTester/app/src/main/res/layout/activity_tap_to_tone.xml

OboeTester: Add noise pulse for Tap to Tone

---

include/oboe/AudioStream.h
src/common/AudioStream.cpp

Limit timeout between stop and close

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
include/oboe/Definitions.h
samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp
samples/powerplay/src/main/cpp/PowerPlayJNI.cpp
samples/powerplay/src/main/cpp/PowerPlayMultiPlayer.cpp

Definitions.h: Rename PowerSavingOffloaded

---

apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTest.h

OboeTester: Fix race conditions in AudioWorkloadTest.h

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java

Enable background operation and foreground service by default.

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_test_output.xml
apps/OboeTester/app/src/main/res/values/strings.xml
include/oboe/AudioStream.h
include/oboe/Definitions.h
include/oboe/ResultWithValue.h
src/aaudio/AAudioLoader.cpp
src/aaudio/AAudioLoader.h
src/aaudio/AudioStreamAAudio.cpp
src/aaudio/AudioStreamAAudio.h

Support flushFromFrame API.

---

apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/PlaybackParameters.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/res/layout/activity_test_output.xml
apps/OboeTester/app/src/main/res/values/strings.xml
include/oboe/AudioStream.h
include/oboe/Definitions.h
include/oboe/Utilities.h
src/aaudio/AAudioLoader.cpp
src/aaudio/AAudioLoader.h
src/aaudio/AudioStreamAAudio.cpp
src/aaudio/AudioStreamAAudio.h
src/common/Utilities.cpp

Support playback parameters.

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BufferSizeView.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivityBase.java
apps/OboeTester/docs/AutomatedTesting.md

Support automation test for offload playback.

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivityBase.java

Only show playback parameter for offload stream.

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BufferSizeView.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivityBase.java
apps/OboeTester/docs/AutomatedTesting.md

Support formats and buffer in frames for automation tests.

---

apps/OboeTester/app/build.gradle
apps/OboeTester/app/src/main/AndroidManifest.xml
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestTimeoutReceiver.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestTimeoutScheduler.java

OboeTester: Use AlarmManager to schedule timeouts

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
apps/OboeTester/docs/AutomatedTesting.md

Support buffer capacity for automation test.

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioForegroundService.java
apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java

Synchronization for starting and stoping foreground service.

---

apps/OboeTester/app/src/main/res/layout/sample_fast_button.xml

Android studio failed to build when I tried to create a signed APK. This seems to solve it

OboeTester: fix issue with schema

---

apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java

OboeTester: Stop stream sniffer when screen is off
