google/oboe

- src/aaudio/AAudioLoader.cpp
Fix issue #6 - they were reversed
> oboe: fix dlsym for getFramesWritten/Read

- include/oboe/OboeStreamCallback.h
This was unused and unimplemented.
Also difficult to implement.
> oboe callback: remove onExit()

- include/oboe/OboeStreamBuilder.h
- include/oboe/OboeStreamCallback.h
- src/aaudio/OboeStreamAAudio.cpp
- src/aaudio/OboeStreamAAudio.h
- src/common/OboeStreamBuilder.cpp
WARNING: API change
Modifies OboeStreamCallback onError methods.
Adds protection against stopping or closing a stream at the same time
that the error callback is being processed.
Fix issue #1
> oboe: automatically stop and close a stream when disconnected

- CMakeLists.txt
- src/common/AudioStreamBuilder.cpp
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioInputStreamOpenSLES.h
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
- src/opensles/EngineOpenSLES.cpp
- src/opensles/EngineOpenSLES.h
- src/opensles/OpenSLESUtilities.cpp
- src/opensles/OpenSLESUtilities.h
- src/opensles/OutputMixerOpenSLES.cpp
- src/opensles/OutputMixerOpenSLES.h
Refactored the OpenSL ES code.
Moved static functions into classes.
Split into an Input and Output stream.
Added RECORD support.
Added some thread safety to EngineOpenSLES.
Fixed some bugs and removed asserts.
> add input capture support to OpenSL wrapper

- tests/CMakeLists.txt
- tests/run_tests.sh
- tests/testUtilities.cpp
For instructions see `run_tests.sh`
> Adding unit tests and testing script

- src/aaudio/AudioStreamAAudio.cpp
From https://github.com/google/oboe/issues/40, it seems that AAudio
on Android 8.0 isn't stable enough. As a safety measure, always
fall back to OpenSL ES on it.
> Do not use AAudio unless running on Android 8.1 or higher

- include/oboe/AudioStream.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/AudioStream.cpp
- src/fifo/FifoBuffer.cpp
- src/fifo/FifoBuffer.h
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamBuffered.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Use FIFO for OpenSL ES.
This will allow blocking read/write calls on a stream without using a callback.
> oboe: add blocking read/write

- include/oboe/AudioStream.h
- src/common/AudioStream.cpp
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioInputStreamOpenSLES.h
Init imRecordInterface to nullptr.
Better logs.
> oboe: cleanup OpenSL ES input

- include/oboe/AudioStream.h
- include/oboe/ErrorOrValue.h
- include/oboe/Oboe.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamBuffered.h
For returning an error code and a frame count, or other value, at the same time.
> oboe: add ErrorOrValue dual return

- src/common/MonotonicCounter.h
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioInputStreamOpenSLES.h
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamBuffered.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
and getFramesWritten for OpenSL ES INPUT.
Query position in milliseconds from OpenSL ES.
Use MonotonicCounter to build 64-bit frame counter from
32-bit internal counter.
Fixes Issue #81
> Implement getFramesRead for OpenSL ES OUTPUT

- include/oboe/AudioStream.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
It is more of a question: most of "get" functions are const, this getFramePerBurst() is not. Is this intentional? after adding "const", it still works.
the benefit is that: user does not have to do something like:
const_cast<AudioStream*>(stream)->getFramesPerBurst() anymore
thanks
> add const modifier to oboe::AudioStream::getFramesPerBurst()

- CMakeLists.txt
by PUBLIC for include directory, it will be automatically included for users using add_subdirectory(); it would also copy to the release directory if there is configures ( I think ).
a little convenience for users: it seems older versions were using public, latest one changed it to private
> Expose header directory to users via CMakeLists.txt

- .ci_tools/build_samples.sh
- .ci_tools/misc_ci.sh
- .ci_tools/run_samples.sh
- .ci_tools/setup_env.sh
- .travis.yml
- README.md
- samples/build.gradle
Adding CI to the repo:
- use samples directory ci every check-in
- only checking build to be successful
The final one should look like this one:
- [repo](https://github.com/ggfan/testOboe)
- [ci-page](https://travis-ci.org/ggfan/testOboe)
If you are interested, let me know. In order for it to work, additional steps:
- enable travis-ci on your repo (only repo owner could do it )
- merge in this pull-request
only then could think of how to do run-time for the built samples ( emulator or firebase ci with devices )
Kindly share your thoughts: if you like it, let's the fun begin
> Adding travis ci to the repo

- README.md
- docs/FullGuide.md
- include/oboe/AudioStream.h
- include/oboe/Version.h
- samples/hello-oboe/src/main/cpp/PlayAudioEngine.cpp
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/LatencyTuner.cpp
- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamBuffered.h
This change (and [this one](https://github.com/google/oboe/pull/87)) add a new object `ResultWithValue` and change some of the `AudioStream` method signatures in the Oboe library.
Some of the `AudioStream` methods would return a positive (or zero) value if they were successful and a negative value if not. For example, consider the following code which attempts to set a stream's buffer size: 
int32_t result = stream->setBufferSizeInFrames(newBufferSize)
if (result < 0){
LOGD("Error setting buffer size: %s", convertToText(static_cast<Result>(result));
} else {
LOGD("New buffer size is: %d", result);
}
The `setBufferSizeInFrames` method is actually returning two pieces of information: 
1) whether the call succeeded or failed
2) the new buffer size if the call succeeded
The method breaks [the …
> ResultWithValue: Doc updates, version bump and code changes

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
hi! i guess this is my public PR :)
anyway, a couple of things here:
* changed the recording preset for OpenSL ES to `SL_ANDROID_RECORDING_PRESET_UNPROCESSED` since it's meant to be used whenever you need raw sound, truly unprocessed (no AGC, no EC, no HPF). [more info](http://source.android.youdaxue.com/compatibility/android-cdd#5_11_capture_for_unprocessed). 
one can read around that the preset to be used for raw sound is `SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION`, but for me (my device is a bq aquaris X pro) that preset, though my recorded voice is clear, didn't gave me pleasant results when i play the guitar and sing and record. it caused some weird artifacts; it was like the background room noise (i guess my own voice echo on walls, street sounds, etc.) sounded like trough they …
> a couple of tweaks for OpenSL ES: UNPROCESSED + Errors on logcat tearing down OpenSL

- src/opensles/AudioStreamOpenSLES.cpp
When there is no stream session id `SL_ANDROID_PERFORMANCE_LATENCY` should be used
When there is a stream session id `SL_ANDROID_PERFORMANCE_LATENCY_EFFECTS` should be used
> Fix incorrect logic for OpenSL ES performance configurations

- src/aaudio/AAudioLoader.cpp
Changed to AAudioStreamBuilder_setInputPreset.
Fixes #131
> audio: fix typo in AAudioStreamBuilder_setinputPreset

- src/opensles/AudioStreamOpenSLES.cpp
This is fixes issue https://github.com/google/oboe/issues/124, and LiveEffect will work for older platforms. Please carefully review it: my reading is that NMR1 began having the feature.
> For OpenSL ES, bypass PERFORMANCE_MODE for android N and older platforms

- src/common/Utilities.cpp
Cache version because it will not change.
> oboe: optimize getSdkVersion()

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioInputStreamOpenSLES.h
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Indexed channel masks were not supported before N.
Fixes #117
> opensles: generate channel masks safely by OS version

- src/aaudio/AudioStreamAAudio.cpp
- src/opensles/AudioStreamBuffered.cpp
- tests/CMakeLists.txt
- tests/run_tests.sh
- tests/testStreamClosedMethods.cpp
Tests added and the following methods have been updated to return `Result::ErrorClosed` when the audio stream is closed 
setBuferSizeInFrames
calculateLatencyInMillis
read 
write
> Tidy up for stream closed default values

- src/common/OboeDebug.h
Defining OBOE_ENABLE_LOGGING 0
Fixes #166
> oboedebug: support disabling of logging

- src/opensles/AudioInputStreamOpenSLES.cpp
- tests/testStreamStates.cpp
This is to match the behavior of AAudio.
Fixes #88
> opensles: make Input pause unimplemented

- tests/CMakeLists.txt
This may only only work on Mac.
> tests: use $ENV{HOME} instead of hard coded name

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
- src/opensles/EngineOpenSLES.cpp
- tests/testStreamOpen.cpp
- tests/testStreamStates.cpp
The LowLatency request was not getting set correctly because
GetInterface was failing.
Also the final PerformanceMode was not being queried after the stream was created.
So it was set to whatever the caller requested instead of the actual value.
Fixes #197
Fixes #179
> opensles: fix PerformanceMode setting

- src/opensles/AudioStreamBuffered.cpp
Fixed a ResultWithValue containing the framesWritten.
Fixes #219
> opensles: fix stall when buffer size changed

- src/aaudio/AudioStreamAAudio.cpp
Workaround for a limitation in AudioFlinger on Legacy AAudio data path.
INPUT stream capacity must be 4096 to get a FAST track.
Fixes #183
> round capacity up to get a FAST input path

- include/oboe/AudioStream.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/AudioStream.cpp
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioInputStreamOpenSLES.h
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamBuffered.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
For better frame counting in OpenSL ES.
When a FIFO was being used, getFramesRead() was returning
the server position. It should return the FIFO position.
Fixes #153
> check usingFifo() for getFramesRead/Written()

- src/fifo/FifoBuffer.cpp
- src/fifo/FifoBuffer.h
- src/opensles/AudioStreamBuffered.cpp
Was clearing beginning of buffer instead of end of buffer.
Also document read() and readNow().
This affects OpenSL ES blocking writes when un underflow occured.
Fixes: 233
Fixes: 154
> fix readNow buffer pointer

- include/oboe/AudioStreamBuilder.h
- include/oboe/AudioStreamCallback.h
- include/oboe/Definitions.h
For example, do not stop() or write() a stream from the callback.
Some of these docs were borrowed from AAudio.
Issue #32
> docs: add restrictions to AudioStreamCallback

- include/oboe/AudioStreamBuilder.h
- src/common/AudioStreamBuilder.cpp
> Fix memory leak if AudioStreamBuilder::openStream() fails.

- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
remove close()
remove some logging
reduced ERROR to WARNING for dlsym() when function not found
> AAudioLoader: cleanup destructor, logging

- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
When size was zero it displayed "0 = -1 * 96".
Now it will display "0 = 0 * 96".
> OboeTester: fix display of buffer size

- CMakeLists.txt
- include/oboe/StabilizedCallback.h
- samples/MegaDrone/README.md
- samples/MegaDrone/src/main/cpp/AudioEngine.cpp
- samples/MegaDrone/src/main/cpp/AudioEngine.h
- src/common/StabilizedCallback.cpp
- src/common/Trace.cpp
- src/common/Trace.h
Adding `LoadStabilizer` class which is a wrapper for `AudioStreamCallback`. It executes the client's callback method, then keeps performing CPU operations for the remaining 80% of the callback in order to keep the CPU frequency high.
> Add LoadStabilizer class

- src/opensles/AudioOutputStreamOpenSLES.cpp
I guess this partly solves issue #168.
I'm not sure about the ContentType. Would that be for AudioInputStreamOpenSLES?
> [code] use the value stored in the builder's Usage in AudioOutputStreamOpenSLES

- include/oboe/Version.h
- src/common/AudioStreamBuilder.cpp
Also bump version to 1.0.1 to avoid confusion with stable 1.0.0 release.
Fixes #304
> oboe: log version number in openStream()

- include/oboe/AudioStream.h
- include/oboe/Utilities.h
- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/AudioStream.cpp
- src/fifo/FifoControllerBase.h
Initialize some variables.
Use atomic counters in FIFO.
Partial fix for #293
> oboe: cleanup aaudio wrapper

- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
- src/opensles/EngineOpenSLES.cpp
- src/opensles/EngineOpenSLES.h
- src/opensles/OpenSLESUtilities.cpp
Better initialization.
Check for negative sizes.
Use switch for error strings.
Partial fix for #293
> oboe: cleanup OpenSL ES wrapper

- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
It broke when I added the "Use Callback" checkbox.
> OboeTester: fix Record and Play

- src/aaudio/AudioStreamAAudio.cpp
AAudio is not returning INVALID_STATE when it should.
Fixes #322
> oboe: return invalid from getTimestamp when stopped

- CMakeLists.txt
- include/oboe/AudioStreamBase.h
- src/common/MonotonicCounter.h
- src/opensles/AudioStreamBuffered.h
- src/opensles/AudioStreamOpenSLES.h
Currently Oboe doesn't work with the JUCE DemoRunner project because it uses [stricter compile flags](https://github.com/WeAreROLI/JUCE/blob/master/examples/DemoRunner/DemoRunner.jucer#L96) causing errors when building Oboe.
This change adds some stricter compile flags and fixes the code which subsequently breaks - mainly where we  were comparing `int32_t` to `uint32_t`.
> Adding stricter compile error flags to make Oboe compatible with JUCE

- include/oboe/AudioStream.h
- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/AudioStream.cpp
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Stop in a separate thread for AAudio before Q.
Call stop directly for OpenSL ES.
Possible fix for #277
> oboe: stop stream if callback requests it

- src/opensles/AudioStreamOpenSLES.cpp
Was logging DataCallbackResult.
This problem was reported by xdaimon here:  
https://github.com/google/oboe/commit/41816f55fcc32a7968f9475013413c29e50369f0#commitcomment-31848378
> Log enqueueResult in OpenSL ES

- src/aaudio/AudioStreamAAudio.cpp
That can close a stream that is in use by the app thread
that is writing the stream.
See issue #359
> oboe: do not use error callback when no data callback

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
Prevents non-callback thread from crashing.
Fixes #374
> OboeTester: check for stream in start()

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
Blocking IO was stopping immediately because of a recent change.
The callback was disabled but blocking IO on OpenSL ES
needs an internal callback to read/write the top level FIFO.
Fixes #370
See bug for repro steps.
> oboe: fix openSL ES read, write

- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
Add _l version to prevent recursive lock from requestStop().
> oboe_opensles: lock requestFlush()

- docs/GettingStarted.md
This makes the GettingStarted docs actually work, rather than relying on the reader to know how to generate a sine wave in code.
> Replace `generateSineWave` with noise generation

- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
Use signatures and helper functions for loading
all AAudio functions.
Use RTLD_NOW in dlopen().
This partially addresses the Chrome security review in https://github.com/google/oboe/pull/352
> oboe: cleanup AAudio loader

- docs/AppsUsingOboe.md
The list of apps/frameworks using Oboe was getting quite long. I've refactored it into a table.
> Refactor list of apps into a table

- include/oboe/AudioStream.h
Since https://github.com/google/oboe/pull/213/commits/6437f5aa224330fbdf77ecc161cc868be663a974, `isPlaying` is no longer part of Oboe's API.
Looks like we forgot to remove the function definition from the header file which made it a pure `virtual` function with no implementation that will error out when called.
> Remove isPlaying from AudioStream header

- CMakeLists.txt
In cmake manner, building shared library is easily doable by specifying
BUILD_SHARED_LIBS option (with `-D` command line argument),
but this explicit `STATIC` specification prevents that.
Since STATIC build is the default, it can be simply removed.
> CMakeLists.txt: make it possible to build shared library

- include/oboe/AudioStreamBase.h
- samples/hello-oboe/src/main/cpp/PlayAudioEngine.cpp
for getChannelCount() and getFramesPerCallback().
> Use int32_t in AudioStreamBase.h

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
The low channel was hard to hear.
Bumped from 440 to 660 for base frequency.
> OboeTester: increase frequency of sine waves

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
Was causing a leaked stream.
Also bumped to 1.3.04
> OboeTester: fix double open in RT LATENCY test

- apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- include/oboe/Definitions.h
- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
This allows Oboe to be compiled with old NDK.
> Eliminate need for AAudio.h

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
It was setting the wrong variable.
This broke a few weeks ago.
Fixes #428
> OboeTester: fix "callback returns STOP" box

- include/oboe/AudioStream.h
- src/aaudio/AudioStreamAAudio.cpp
- src/opensles/AudioStreamOpenSLES.cpp
- tests/CMakeLists.txt
- tests/testStreamWaitState.cpp
Test closing the stream from one thread while calling waitForStateChange in another thread.
Also fix the OpenSL ES implementation so it matches the AAudio implementation.
> test waitForStateChange

- apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
oboe/apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h:650:20: error: unused variable 'latencyMillis' [-Werror,-Wunused-variable]
double latencyMillis = kMillisPerSecond * (double) mLatencyReport.latencyInFrames
^
oboe/apps/OboeTester/app/src/main/cpp/NativeAudioContext.h:104:13: error: unused variable 'scheduler' [-Werror,-Wunused-variable]
int scheduler = audioStreamGateway.getScheduler();
^
> Fix build errors

- include/oboe/AudioStream.h
`AudioStream.h` uses both `std::atomic` and `std::mutex`. It should have these headers included. Fixes #392
> Add <atomic> and <mutex> to AudioStream includes

- tests/testStreamStates.cpp
This is to prevent a race condition on the emulator from
causing some tests to fail.
Fixes #425
> tests: sleep between close and open

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/EchoActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
Use KEEP_SCREEN_ON to allow tests to run overnight.
Keep the phone plugged in.
> OboeTester: add screen wake locks

- apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
The noise was an attempt to reduce effect of dynamic range control.
But it was too noisy.
> OboeTester: set noise amplitude to zero

- samples/LiveEffect/src/main/cpp/CMakeLists.txt
- samples/LiveEffect/src/main/cpp/FullDuplexPass.h
- samples/LiveEffect/src/main/cpp/FullDuplexStream.cpp
- samples/LiveEffect/src/main/cpp/FullDuplexStream.h
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
Refactoring Live Effect to use Full Duplex stream. Having a separate effect engine and duplex stream is a little redundant. But, the duplex stream class does not take ownership of stream creating and closure, so a second class is still necessary.
> Refactor Live Effect to use Full Duplex Stream

- samples/MegaDrone/src/main/cpp/Synth.h
- samples/MegaDrone/src/main/cpp/native-lib.cpp
- samples/MegaDrone/src/main/java/com/example/oboe/megadrone/MainActivity.java
- samples/RhythmGame/src/main/cpp/Game.cpp
- samples/RhythmGame/src/main/cpp/Game.h
- samples/shared/Mixer.h
> Reinit. Audio Engine for MegaDrone on restart.

- include/oboe/AudioStreamBuilder.h
- samples/LiveEffect/src/main/cpp/CMakeLists.txt
- samples/LiveEffect/src/main/cpp/FullDuplexPass.h
- samples/LiveEffect/src/main/cpp/FullDuplexStream.cpp
- samples/LiveEffect/src/main/cpp/FullDuplexStream.h
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
- samples/MegaDrone/src/main/cpp/Synth.h
- samples/MegaDrone/src/main/cpp/native-lib.cpp
- samples/MegaDrone/src/main/java/com/example/oboe/megadrone/MainActivity.java
- samples/RhythmGame/src/main/cpp/Game.cpp
- samples/RhythmGame/src/main/cpp/Game.h
- samples/hello-oboe/src/main/cpp/PlayAudioEngine.cpp
- samples/hello-oboe/src/main/cpp/PlayAudioEngine.h
- samples/shared/Mixer.h
See issue #527 for more details.
> Adding a Copy Constructor to AudioStreamBuilder

- include/oboe/AudioStream.h
- include/oboe/AudioStreamBuilder.h
- samples/hello-oboe/src/main/cpp/PlayAudioEngine.cpp
- samples/hello-oboe/src/main/cpp/PlayAudioEngine.h
- src/common/AudioStream.cpp
- src/common/AudioStreamBuilder.cpp
Adding easy support for uniqueptrs of AudioStreams via a ManagedStream type. This type has a custom deleter which closes the AudioStream to safely delete it. ManagedStream can be treated as a generic object, with AudioStreamBuilder safely repopulating a ManagedStream with the openManagedStream method. (This assumes close() is thread safe/safe to repeat).
Also refactoring Hello-Oboe to use this type. (This assumes onErrorAfterClose is safe).
> Adding ManagedStream type

- include/oboe/AudioStream.h
- include/oboe/AudioStreamCallback.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
There was a race that could be caused by multiple onErrorCallbacks.
There should only be one callback.
We now check to make sure that only the first callback is handled.
Fixes #519
> oboe: prevent onError callback from causing an assert

- samples/MegaDrone/src/main/cpp/native-lib.cpp
- samples/MegaDrone/src/main/java/com/example/oboe/megadrone/MainActivity.java
Avoids having a raw pointer which requires manual deletion.
> [samples/MegaDrone] Move ownership of AudioEngine into Java

- src/common/AudioStreamBuilder.cpp
One line fix to properly delete (and close) old ManagedStream objects.
> Fixing bug in AudioStreamBuilder causing leak

- src/fifo/FifoController.cpp
- src/fifo/FifoController.h
- src/fifo/FifoControllerBase.cpp
- src/fifo/FifoControllerBase.h
- src/fifo/FifoControllerIndirect.cpp
- src/fifo/FifoControllerIndirect.h
This addresses some of the comments in #352. It makes
FifoControllerBase's getters consts, and it uses default destructors.
> Mark Fifo getters as consts

- src/fifo/FifoBuffer.cpp
- src/fifo/FifoController.h
- src/fifo/FifoControllerBase.cpp
- src/fifo/FifoControllerBase.h
- src/fifo/FifoControllerIndirect.h
This CL adds an increment counter methods that allow for atomically
incrementing the read/write indexes, rather than geting the current
index, adding to it and setting it.
Also, getFullFramesAvailable() and getEmptyFramesAvailable() now clamp
negative values to 0.
> Add atomic increment to FifoControllers

- include/oboe/AudioStream.h
An abstract method was breaking the linker stage.
Fixes #582
> oboe: fix broken build AudioStream.cpp

- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Following up on comments from #352 
This patch updates AudioStreamOpenSLES to use std::vector instead of
managing its own memory.
> Wrap uint8_t[] with unique_ptr

- CMakeLists.txt
Allows Oboe to be included as an external project using CMake's `ExternalProject_Add` function. Also adding install targets which places binaries and headers in the following directory structure: 
CMAKE_INSTALL_PREFIX/
lib/
arm64-v8a/liboboe.a
armeabi-v7a/liboboe.a
x86/liboboe.a
x86_64/liboboe.a
include/
oboe/<all headers>
> Improve CMake config

- include/oboe/AudioStream.h
- include/oboe/AudioStreamCallback.h
Allows clients to use stronger compiler warning flags  (like Wall).
> Commenting out parameters to use Wall compiler flag

- samples/LiveEffect/src/main/cpp/FullDuplexStream.cpp
stop() died because of null stream
> LiveEffect: fix crash if audio permission needed

- include/oboe/Version.h
- src/common/AudioStreamBuilder.cpp
Fixes #655
Bump Oboe version to 1.2.1
> oboe: change default buffer sizes for INPUT

- src/common/AudioStreamBuilder.cpp
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
If we do not get a low latency stream, then use a bigger burst.
We were getting a 96 frame burst on some devices without a FAST track,
which is too small.
> oboe: use bigger burst in OpenSL ES

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
- apps/OboeTester/app/src/main/cpp/FullDuplexStream.cpp
- apps/OboeTester/app/src/main/cpp/LatencyAnalyzer.h
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
Keep analysing even if we do not read the desired number of frames.
This will allow glitch detection and latency measurement when combining
streams with very different burst sizes.
Fixes #485
Fixes #618
> Oboetester: do not reset full duplex analyzer

- include/oboe/Version.h
- src/opensles/AudioStreamBuffered.cpp
Round it up to some number of bursts.
This may fix some glitching when doing blocking I/O.
> oboe: make sure OpenSL ES buffer capacity is OK

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfiguration.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/StreamConfigurationView.java
Set defaults to FLOAT format and FLoatFormatConversionAllowed(true).
This fixes the problem where OpenSL ES will not get a LOW Latency
stream for input.
Then the glitch and latency tests may fail.
> OboeTester: use FLOAT for Analyzer

- include/oboe/Version.h
- src/opensles/AudioStreamOpenSLES.cpp
Only increase the framesPerBurst for OpenSL ES for low latency
streams for SDK >= N_MR1.
Round to multiple of original framesPerBurst above 960.
Bump version to 1.2.4
Fixes #694
> oboe: bump OpenSL framesPerBurst by version

- apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/InfiniteRecording.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/WaveformView.java
- apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml
Grab the last glitch from the GlitchAnalyser and display the waveform.
It is possible to recognize the source of the glitch from the shape.
> OboeTester: add glitch display

- samples/MegaDrone/src/main/cpp/native-lib.cpp
Call ReleaseIntArrayElements()
and simplify vector initialization.
Fixes #713
> MegaDrone: fix memory leak in JNI

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioOutputTester.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamTester.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioOutputStream.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestInputActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/WorkloadView.java
- apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
- apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml
- apps/OboeTester/app/src/main/res/layout/workload_view.xml
This can be used to stress the system and cause glitches.
It can also be used to make race conditions more likely.
> OboeTester: add Workload fader that will burn up the CPU

- apps/OboeTester/app/src/main/res/values/strings.xml
Add 11025, 12000, 24000 Hz.
Fixes #739
> Add more sample rates to OboeTester

- src/flowgraph/resampler/IntegerRatio.cpp
- src/flowgraph/resampler/IntegerRatio.h
Using global variables in c++ gives the problems with integrating with other languages.
In particular the linking errors like that: https://github.com/rust-lang/rust/issues/36710.
So I think we can and should avoid global variables at all.
> Avoid global variables

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Use smaller buffer sizes for lower rates.
Base on 20 msec period common on Android.
Pass mSampleRate so caller can guarantee it is set.
Fixes #751
> opensles: scale buffer size by sample rate

- apps/OboeTester/scripts/dsp_timing.py
Determine the timing profile for the DSP.
This only works on versions of Android
that support "aaudio.out_mmap_offset_usec" property.
> OboeTester: measure glitches vs DSP time offset

- samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
- samples/LiveEffect/src/main/cpp/jni_bridge.cpp
- samples/LiveEffect/src/main/java/com/google/sample/oboe/liveEffect/LiveEffectEngine.java
- samples/LiveEffect/src/main/java/com/google/sample/oboe/liveEffect/MainActivity.java
- samples/LiveEffect/src/main/res/values/strings.xml
Used to crash on a nullptr.
Now it passes the result up to Java.
Also uses ManagedStream to prevent leaked resources.
Bug: #796
> LiveEffect: handle failure to open the stream

- .travis.yml
seems ok w/o lldb, let's remove.
> Fixing lldb 3.1 installation failure in ci

- apps/OboeTester/app/build.gradle
Default to building: arm32, arm64, x86_32, and x86_64 ABIs. Handy
for testing intel-based devices like Chromebooks.
> Default to building both x86 and ARM ABIs

- include/oboe/Version.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Move call to getPosition() outside the callback.
This was triggering a restoreTrack_l() inside
AudioFlinger folowing a headset insertion.
That in turn caused an assert in releaseBuffer() in
AudioTrack or AudioRecord.
Now it is called when needed by getFramesRead() or getFramesWritten().
Fixes ##535
> opensles: prevent crash in releaseBuffer()

- docs/notes/disconnect.md
The [documentation](https://developer.android.com/reference/android/content/Intent#ACTION_HEADSET_PLUG) of `Intent.ACTION_HEADSET_PLUG` recommends to use `AudioManager.ACTION_HEADSET_PLUG` instead if min sdk _is_ LOLLIPOP. It is unclear if it means min sdk is _at least_ LOLLIPOP. It may be worth mentioning it here.
> corrected intent constant

- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/MainActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/NativeEngine.java
It was getting out of sync with the model.
Now we update the view based on the model in onResume.
Fixes #818
> OboeTester: fix state of workarounds checkbox

- CMakeLists.txt
- src/common/DataConversionFlowGraph.cpp
- src/common/DataConversionFlowGraph.h
- src/common/QuirksManager.cpp
- src/common/QuirksManager.h
- src/flowgraph/ChannelCountConverter.cpp
- src/flowgraph/ChannelCountConverter.h
- src/flowgraph/MultiToMonoConverter.cpp
- src/flowgraph/MultiToMonoConverter.h
The Samsung S9 does not support mono properly.
It is actually stereo. So on that device, we open a stereo
stream and then convert it to mono by extracting
the first channel.
Fixes #824
> oboe: add Quirk for broken mono on S9

- src/aaudio/AudioStreamAAudio.cpp
AAudio returns confusing error codes when an open
fails due to permission errors. Suggest a possible reason.
Related to #888
> oboe: warn user of permission errors

- samples/drumthumper/build.gradle
As per guidance here: https://developer.android.com/studio/build/application-id I have created a different build flavor which changes the `applicationId` to `com.mobileer.drumthumper` suitable for publishing to the Play Store.
> [samples/DrumThumper] Add build flavor for publishing to Play Store

- apps/OboeTester/app/CMakeLists.txt
- tests/CMakeLists.txt
This fixes a problem with AAudio calling flowgraph module
destructors in Oboe, which causes memory corruption.
Fixes #930
> build: use -fvisibility=hidden

- samples/drumthumper/README.md
- samples/drumthumper/src/main/java/com/google/oboe/samples/drumthumper/DrumPlayer.kt
Make explicit the limitation on the input samples (44.1K, mono, PCM16)
https://github.com/google/oboe/issues/913
> Clarify the scope of the DrumThumper app.

- tests/testAAudio.cpp
Was failing if AAudio not supported.
AAudio is only supported on 8.1 and later.
> unit tests: fix direct AAudio test

- apps/OboeTester/app/src/main/cpp/AudioStreamGateway.cpp
- apps/OboeTester/app/src/main/cpp/AudioStreamGateway.h
- src/common/DataConversionFlowGraph.cpp
- src/flowgraph/FlowGraphNode.cpp
- src/flowgraph/FlowGraphNode.h
- src/flowgraph/SinkFloat.cpp
- src/flowgraph/SinkFloat.h
- src/flowgraph/SinkI16.cpp
- src/flowgraph/SinkI16.h
- src/flowgraph/SinkI24.cpp
- src/flowgraph/SinkI24.h
There was a problem with disconnecting modules
that could cause high pitched sounds in OboeTester.
This patch simplifies the logic for handling cyclic graphs
and split graphs.
Fixes #902
> flowgraph: improve Oboe flowgraph

- tests/testFlowgraph.cpp
The internal read() method in flowgraph changed as part of #935.
This patch updates the tests so they compile.
> flowgraph test: update read() API

- src/fifo/FifoBuffer.cpp
- src/fifo/FifoBuffer.h
- src/fifo/FifoController.cpp
- src/fifo/FifoController.h
- src/fifo/FifoControllerBase.cpp
- src/fifo/FifoControllerBase.h
- src/fifo/FifoControllerIndirect.cpp
- src/fifo/FifoControllerIndirect.h
Remove AudioClock.h and other unnecessary includes.
Fixes #927
> oboe: cleanup fifo includes

- samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
Related issue: https://github.com/google/oboe/issues/956
> live-effect: use playback stream sample rate to open record stream

- .github/ISSUE_TEMPLATE/bug_report.md
Phil usually requests `ro.hardware.chipname` and `ro.arch` which don't exist on my devices. So additionally I added related properties I found.
> Added device section for bug report template

- tests/run_tests.sh
.. otherwise shebang won't be taken into account and the script will run in the default shell.
When I ran the original script, it ran on my zsh and produced errors (Ubuntu/Linux).
Moving shebang to the top fixes the issue as the script run in bash as expected.
> fixed shebang in run_tests.sh

- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
This is a workaround for a possible callback after close that can occur
if close is called immediately after a stop.
This can occur on P, particularly when using Bluetooth devices.
Fixes #967
> oboe: delay before closing an AAudio stream

- tests/testStreamOpen.cpp
This replaces PR #553 which had a tangled merge.
Oboe is returning ErrorInternal for invalid formats.
See #989 for adding more parameter checks.
> tests: test for invalid formats with OpenSL ES

- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
Hitting Back button while in the middle of the
Auto Glitch Test could cause a crash.
I was calling closeAudio when the test thread finished.
AND I was calling closeAudio() from the Activity onStop() call.
They were colliding as I deleted the Oboe Stream.
So I synchronized the closeAudio() method and protected it with a new CLOSING state.
> OboeTester: fixed crash when exiting Auto Glitch Test

- samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
At the app starting up time, inside the HelloOboeEngine constructor, mStream would always nullptr as no allocation to the raw pointer yet; when calling into HelloOboeEngine::start(), so it would still be nullptr, so check for nullptr would always fail, hence mStream would never get chance to be allocated; when later calling into HelloOboeEngine::tap(), a nullptr is dereferenced, resulting to a crash.
Since builder->openStream() reset the share_ptr, it could tolerate a nullptr. The fix is enable nullptr case in mStream in this sample, there will not be memory leak side-effect.
> Simple fix to hello-oboe related to shared_ptr

- src/common/AudioStreamBuilder.cpp
- src/common/DataConversionFlowGraph.cpp
- src/common/QuirksManager.cpp
Avoid using callback size adapters in AAudio because of various bugs.
If setFramesPerCallback() called then use a filter stream and do the
block size adaptation in Oboe as part of the data conversion flowgraph.
Fixes #778
Fixes #973
Fixes #983
> oboe: use proxy for callback size adapter

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AnalyzerActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/ManualGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
Use with automated latency and glitch test.
For example: -es in_api opensles
Fixes #944
> OboeTester: support OpenSLES in automated tests

- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
This will give the callback threads time to exit
before the stream is destroyed and will help avoid
some race conditions inside AAudio and AudioFlinger.
Fixes #961
> oboe: force a stop() before close()

- samples/parselib/src/main/cpp/wav/WavStreamReader.cpp
Skipped chunks should now be skipped properly without crashing.
> fixes #1027 handling of skipped chunks during wav parse

- samples/MegaDrone/src/main/cpp/MegaDroneEngine.cpp
- samples/MegaDrone/src/main/cpp/MegaDroneEngine.h
- samples/MegaDrone/src/main/cpp/native-lib.cpp
To lift stream creation from constructor to a public start() function: this is a followup from [the shared_ptr change pull request](https://github.com/google/oboe/pull/1016), PTAL
> Minor update to MegaDrone sample for stream creation

- src/opensles/AudioStreamOpenSLES.cpp
It used to not timeout and would spin until the state changed.
Fixes #1061
> oboe: fix timeout in waitForStateChange() for OpenSL ES

- samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
- samples/hello-oboe/src/main/cpp/HelloOboeEngine.h
- samples/hello-oboe/src/main/cpp/jni_bridge.cpp
It was crashing when the app was closed because
the stream was still running when the engine was deleted.
Now the stream is stopped and closed before deleting.
Also moved start() out of constructor.
> HelloOboe: fix crash on exit

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.cpp
The error message said it wasn't supported but it actually is.
Fixes #1043
> oboe: remove InputPreset warning in OpenSL ES.

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestDisconnectActivity.java
- include/oboe/AudioStream.h
- include/oboe/AudioStreamBase.h
- include/oboe/AudioStreamBuilder.h
- include/oboe/AudioStreamCallback.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/AudioSourceCaller.cpp
- src/common/AudioStream.cpp
- src/common/DataConversionFlowGraph.cpp
- src/common/FilterAudioStream.cpp
- src/common/FilterAudioStream.h
- src/common/QuirksManager.cpp
- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamBuffered.h
- tests/testStreamClosedMethods.cpp
This allows an app to use different callbacks for data processing
and error processing. The AudioStreamCallback inherits
from both interfaces.
There is also a new method: bool onError()
that allows an app to completely override the default
error handling.
This change is backwards compatible with older versions.
Fixes #917
> oboe: add AudioStreamDataCallback and AudioStreamErrorCallback

- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamBuffered.h
- src/opensles/AudioStreamOpenSLES.cpp
Check for errors from getFramesWritten().
Preserve const pointer in transfer().
Check for errors from updateServiceFrameCounter().
Check for overflows in capacity calculation.
Fixes #590
> oboe: some code cleanup suggested by Chrome

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Change AudioStreamOpenSLES::close() to close_l() to indicate that it must be called under mLock.
The subclasses acquire the lock.
No runtime change. Just a name change.
Fixes #591
> oboe: change close() to close_l() for OpenSL

- samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp
Missed the "startStream()" call in onErrorAfterClose() after refactor.
> DrumThumper, fix restart on device change.

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioInputStreamOpenSLES.h
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
Do not unlock when stopping the stream.
Call requestStop_l() or requestPause_l().
Fixes #1062
> oboe: prevent race condition in OpenSL close()

- include/oboe/AudioStreamBase.h
- include/oboe/AudioStreamBuilder.h
- src/aaudio/AudioStreamAAudio.cpp
- src/common/AudioStreamBuilder.cpp
- src/common/DataConversionFlowGraph.cpp
- src/common/QuirksManager.cpp
- src/common/Utilities.cpp
The `*FramesPerCallback` methods are now ambiguous because there are 2 callback interfaces. This change deprecates the  `*FramesPerCallback` methods and adds `*FramesPerDataCallback` methods which are unambiguous.
> Add *FramesPerDataCallback and deprecate *FramesPerCallback methods

- src/common/FilterAudioStream.h
- src/opensles/AudioInputStreamOpenSLES.cpp
The InputPreset can be coerced from VoicePerformance to
VoiceRecognition. But getInputPreset() returned the wrong value.
Fixed for FilterAudioStream and OpenSL ES.
Fixes #1090
> oboe: return correct InputPreset when modified

- docs/FAQ.md
- docs/FullGuide.md
- docs/GettingStarted.md
- docs/OpenSLESMigration.md
- docs/notes/disconnect.md
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
- samples/MegaDrone/src/main/cpp/MegaDroneEngine.cpp
- samples/MegaDrone/src/main/cpp/MegaDroneEngine.h
- samples/RhythmGame/src/main/cpp/Game.cpp
- samples/RhythmGame/src/main/cpp/Game.h
- samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
- samples/hello-oboe/src/main/cpp/HelloOboeEngine.h
- samples/hello-oboe/src/main/cpp/LatencyTuningCallback.cpp
- samples/hello-oboe/src/main/cpp/LatencyTuningCallback.h
- samples/shared/DefaultDataCallback.h
- samples/shared/DefaultErrorCallback.h
This PR refactors the sample code away from using a single callback (`AudioStreamCallback`) for both data and error events to using the new `AudioStreamDataCallback` and `AudioStreamErrorCallback` classes. 
The only issue I faced was that the original `DefaultAudioStreamCallback` (used by hello-oboe and megadrone) would attempt to set thread affinity inside the data callback and would reset it inside the error callback through a single field: `mIsThreadAffinitySet`. 
By separating the two callbacks the error callback no longer has access to this field. To solve this I added a `reset` method to `DefaultDataCallback` which can be called to reset the data callback to its initial configuration (in this case, only the thread affinity). 
The responsibility for calling `reset` moves away from …
> Update sample code and documentation to use new data and error callback interfaces

- samples/LiveEffect/src/main/cpp/FullDuplexPass.h
- samples/LiveEffect/src/main/cpp/FullDuplexStream.cpp
- samples/LiveEffect/src/main/cpp/FullDuplexStream.h
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
- samples/LiveEffect/src/main/cpp/jni_bridge.cpp
Use std::shared_ptr in FullDuplexStream.
Explicitly process the samples in the callback instead
of just using memcpy. This will be easier to modify.
Fixes #1113
Fixes #852
> Liveeffect: fix crash on exit

- apps/OboeTester/app/CMakeLists.txt
- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
These caused the Oboe build to fail if OBOE_NO_INCLUDE_AAUDIO
was defined.
Fixes #1122
> oboe: define missing AAUDIO constants

- src/common/QuirksManager.cpp
- src/common/QuirksManager.h
Move definition to QuirksManager.h
so it can be used by other files.
Fixes #1148
> oboe: move __ANDROID_API_R__

- apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/AudioStreamBase.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/RoundTripLatencyActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestAudioActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml
- apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
- apps/OboeTester/app/src/main/res/layout/stream_config.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
Measure 5 times for average.
Change average.latency.msec to mean.latency.msec
Report mean.absolute.deviation
Display min/average/max latency based on timestamp.
Increase max measurable latency to about 960 msec.
> OboeTester: improve latency measurement

- src/common/FilterAudioStream.h
- tests/testStreamOpen.cpp
> Check for nullptr in FilterAudioStream::getTimestamp()

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
To suppress the undefined variable error when the LOGD line is not compiled in, we can add in an ignore command. Similar to discussion here: https://herbsutter.com/2009/10/18/mailbag-shutting-up-compiler-warnings/
> Suppress warnings of unused variable.

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/EchoActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/GlitchActivity.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/NativeSniffer.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/OboeAudioStream.java
- apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestDataPathsActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_echo.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
For input, measured from call to openStream() until first frame arrives to app.
For output, measured from open until first frame hits speaker.
> OboeTester: report cold start latency

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- src/aaudio/AAudioExtensions.h
- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
- src/aaudio/AudioStreamAAudio.cpp
- src/common/AudioStreamBuilder.cpp
- src/common/QuirksManager.cpp
- src/common/QuirksManager.h
The S20 input had some glitches in an early version.
So we turn off MMAP in that case.
We also moved the AAudioExtensions class from OboeTester into Oboe.
Fixes #892
> oboe: add quirk for S20 input

- samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
- samples/LiveEffect/src/main/cpp/jni_bridge.cpp
- samples/LiveEffect/src/main/java/com/google/oboe/samples/liveEffect/LiveEffectEngine.java
- samples/LiveEffect/src/main/java/com/google/oboe/samples/liveEffect/MainActivity.java
The old code was using isAAudioSupported.
AAudio is supported on Android 8.0 but is
not recommended because it can crash.
Fixes #1192
> LiveEffect: use isAAudioRecommended()

- CMakeLists.txt
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- include/oboe/AudioStream.h
- include/oboe/AudioStreamBase.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/FilterAudioStream.h
- src/opensles/AudioStreamBuffered.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Protect native stream pointer with a shared_lock.
The race may have never ended badly.
But it was theoretically possible. So this prevents it.
Note that this requires that Oboe be built with C++17.
But apps can still use C++14.
Fixes #1180
> oboe: fix possible race on close

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
> OboeTester: remove log spew from debugging

- samples/RhythmGame/src/main/cpp/audio/FFMpegExtractor.cpp
Currently in FFMpegExtractor for clearing out packets the following two lines are being used,
```
avPacket.size = 0;
avPacket.data = nullptr;
```
This might create memory leak if someone tries to reuse this implementation in some other project. I am writing an application which is reading data from device storage and decoding using FFMpeg. I did found this implementation very compact, organised and ready to be used. But when I used it and profiled memory, I got below,
Memory block equal to the same size of the decompressed audio remains as ghost memory in RAM.
Doing with the appropriate function,
```
av_packet_unref(&avPacket);
```
Does not leave any memory leak like below,
I know this is a very small contribution, but I hope it will be merged. :)
> RhythmGame FFMpegExtractor - for clearing packet use av_packet_unref

- src/common/QuirksManager.cpp
When opening a mono MMap input stream on Exynos850 devices the stream actually contains stereo data. When playing this data it sounds pitched down by an octave. 
This PR applies the existing workaround for this bug to Exynos850 devices.
Fixes #1247
> Add workaround for Exynos850 devices

- tests/UnitTestRunner/app/src/main/java/com/google/oboe/tests/unittestrunner/MainActivity.java
- tests/UnitTestRunner/build.gradle
- tests/UnitTestRunner/gradle/wrapper/gradle-wrapper.properties
- tests/run_tests.sh
- tests/testStreamOpen.cpp
I've also split the unit test fixtures into `StreamOpenOutput` and `StreamOpenInput` so that it's easy to run these tests in isolation using: 
```
testOboe --gtest_filter=StreamOpenOutput.*
```
This is useful when testing on the emulator which doesn't allow input streams to be opened, and thus causes all the associated tests to fail.
> Fix failing unit tests on pre-L devices

- src/common/QuirksManager.cpp
- tests/testStreamOpen.cpp
Add quirk to allow float playback streams to be created on pre-L devices by using format conversion.
> Support float on jellybean

- samples/RhythmGame/CMakeLists.txt
- samples/RhythmGame/build.gradle
- samples/RhythmGame/src/main/cpp/Game.cpp
- samples/RhythmGame/src/main/cpp/Game.h
- samples/RhythmGame/src/main/cpp/audio/FFMpegExtractor.cpp
- samples/RhythmGame/src/main/java/com/google/oboe/samples/rhythmgame/MainActivity.java
**Change to floats**
Change the RhythmGame sample to only use floats, relying on Oboe's own format conversion when the underlying stream is not float. This makes the code simpler and the sample possible to run on API 16 (using the FFmpeg build variant). 
**Fix the way that libraries are packaged**
The FFmpeg variant was failing to run because the Android Gradle Plugin changed the way it handles imported libraries. It was failing with the error: 
```
2 files found with path 'lib/x86/libswresample.so'.
If you are using jniLibs and CMake IMPORTED targets, see
https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```
The solution was to remove the `jniLibs` block from `build.gradle` and add `System.loadLibrary` into `MainActivity` for the FFmpeg build variant.
Note: This PR …
> Update RhythmGame sample to use format conversion for API 16 compatibility + fix libraries

- tests/CMakeLists.txt
- tests/testStreamFramesProcessed.cpp
- tests/testStreamFramesWritten.cpp
Add unit tests that open input/output stream and process data for a
while and then verify the returned value from getFramesWritten is
correct.
Fixes #1256.
> Add unit tests for testing getFramesWritten returns correctly.

- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
- src/aaudio/AudioStreamAAudio.cpp
OboeStreamCallbackProxy extended AudioStreamDataCallback
But it was being cast to AudioStreamCallback.
So disconnects could cause a crash because of missing methods.
Now it extends AudioStreamCallback.
> OboeTester: fix cast of proxy callback.

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
This is because we changed the package names when we released
OboeTester on Play Store. That caused a breaking change in the
Automated Test related commands.
> OboeTester: bump to V2.0.0

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
setChildrenEnabled is called whenever the state changes between open, started, paused, stopped, and closed. When the stream is closed, all the spinners and checkboxes should work as expected. Otherwise, disable all of them.
This change fixes the user complaints about MMAP not working as expected when the checkbox is toggled by removing the ability to toggle the checkbox
> Update Spinners and CheckBoxes to clean up automatically

- src/common/FilterAudioStream.h
Fixed a missing parameter in FilterAudioStream. Without this change, when getDeviceId() is called, the device id is set to 0, as it uses the default value. With this change, mDeviceId correctly uses the value from the child stream.
I verified that the issue repros before the change and the fix does indeed fix the problem
> Added mDeviceId to FilterAudioStream

- src/flowgraph/RampLinear.cpp
- tests/testFlowgraph.cpp
Currently this ramp starts at 0 for the first ramp for no reason. Start this at the initial volume set.
This will help with clicking issues when pressing the volume up and down keys.
Tested via: Installed and ran updated tests via UnitTestRunner app
> Start linear ramps at the initial volume set

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
In MainActivity.java, there is code to toggle SCO on and off.
```
public void onStartStopBluetoothSco(View view) {
CheckBox checkBox = (CheckBox) view;
AudioManager myAudioMgr = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
if (checkBox.isChecked()) {
myAudioMgr.startBluetoothSco();
} else {
myAudioMgr.stopBluetoothSco();
}
}
```
This code used in conjunction with the use of startBluetoothSco() and stopBluetoothSco() causes several weird cases with SCO and A2DP. The main one is that when SCO was toggled on, TestAudioActivity would not know and SCO would never turn off.
Oboe's overarching philosophy is to let failures happen, so we removed the automatic sco adjustment in this Pull Request
Tested with Boltune and Sony devices on Pixel 4a 5G device
> Fix switching between SCO and A2DP

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java
Fixes #1324
OboeTester crashes when starting a OpenSL ES stream using PCM_I32/PCM_I24 formats. Fix is to simply send an error toast on invalid openStream calls instead of crashing.
Verified that the toast indeed shows on Bramble.
> Show error toast on bad input combinations

- tests/testStreamOpen.cpp
Fixes https://github.com/google/oboe/issues/1270. 
Verified on API 19 emulator and Pixel 4A running Android 12.
> Update format conversion test

- samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
Fixes #1261 by proving that float->int16 conversion does work as intended on API <21.
> [hello-oboe] Add format conversion for output API <21 and input API <23

- docs/FAQ.md
AFAIK Java still has ~20ms greater latency than Oboe. I think it's important to mention this since it's one of the main reasons for Oboe's existence.
> Added note about higher latency in Java

- src/aaudio/AudioStreamAAudio.cpp
- src/common/FilterAudioStream.h
- src/flowgraph/ManyToMultiConverter.h
Fixes #312
The compiler flag -Wunused-parameter outputs some warnings on a couple of files. This is fixed in this PR.
Tested via:
Temporarily added -Wunused-parameter to CMakeLists.txt in top level directory and compiled OboeTester.
> Fix unused-parameter warnings

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneTester.java
- apps/OboeTester/app/src/main/res/values/strings.xml
Prevent users from double tapping in tap-to-tone.
Fixes #1341
> OboeTester: prevent double tap

- include/oboe/AudioStream.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/AudioStream.cpp
- tests/CMakeLists.txt
- tests/run_tests.sh
- tests/testReturnStop.cpp
- tests/testStreamFramesProcessed.cpp
Use another thread to stop the stream for R and earlier.
Fixes #1230.
Test: use OboeTester "callback return STOP" checkbox
> oboe: improve DataCallbackResult::Stop handling

- src/aaudio/AAudioLoader.h
This is to prevent a merge conflict with Android /external/oboe.
It does not seem necessary. __NDK_MAJOR__ is getting defined somewhere else.
Fixes #1358
> oboe: remove include of ndk-version.h

- include/oboe/AudioStreamBuilder.h
In AAudio, we changed GetPackageName to better reflect its usage. Doing the same in Oboe
> Update GetPackageName header

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MidiTapTester.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java
- apps/OboeTester/app/src/main/res/xml/service_device_info.xml
Fixed crash caused by opening Tap-to-Tone when an old
version of OboeTester was also installed.
Fixed the use of MIDI in Tap-to-Tone.
Fixes #1360
> OboeTester: fix MIDI and crash

- tests/testAAudio.cpp
- tests/testStreamOpen.cpp
It seems to be a small mistake.
testAAudio.cpp and testStreamOpen.cpp have dupilicated "#include"
> remove duplicated header

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AnalyzerActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseOboeTesterActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/EchoActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExternalTapToToneActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExtraTestsActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RecorderActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TapToToneActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
Now we ask for permission in the main Activity when
the test is launched.  That allows us to keep the code in one place
but also only ask for permission when we need to record.
Fixes #1364
> OboeTester: refactor RECORD_AUDIO permissions

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceInfoConverter.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_data_paths.xml
- apps/OboeTester/app/src/main/res/layout/activity_device_report.xml
- apps/OboeTester/app/src/main/res/layout/activity_test_disconnect.xml
- apps/OboeTester/app/src/main/res/layout/auto_test_runner.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
Search loop was not updating minDifferences.
Now show all tests at seme level of closeness.
Add checkboxes for data path subtests.
Improve instructions for DISCONNECT and DATA PATHS.
Reenable VoiceCommunication tests.
Fix GLITCH test after DATA PATHs. Mono was broken because
the outputChannel was left at 1.
Add Inertial scrolling of test results.
Bump OboeTester to 2.2.1
Fixes #1371
> OboeTester: fix closest test search

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/DataPathAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
- src/aaudio/AAudioExtensions.h
Fix not setting MMAP policy on first test.
Fix glitches caused by input buffer capacity too small.
Reset magnitude at test beginning so silence can be detected.
Display phase measurement count.
Reduce noise signal.
> OboeTester: improve data paths test, fix capacity glitches

- apps/OboeTester/app/src/main/AndroidManifest.xml
The automatic glitch test runs fine until it tries to save the results. At that point, a toast shows up mentioning how there is a lack of permissions to save the results. The error message is similar to that mentioned here: https://stackoverflow.com/questions/61406818/filenotfoundexception-open-failed-eperm-operation-not-permitted-during-saving
The fix is to add android:requestLegacyExternalStorage="true" into the app manifest
> Fix permission issues for test glitches

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
In OboeTester, sawtooth waves are not played correctly. This Pull Request fixes this.
Fixes #1391
> (OboeTester) Fix sawtooth waves with test output

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
- apps/OboeTester/docs/AutomatedTesting.md
Add automatic data paths tests with the following parameters:
> --ez use_input_presets  {boolean}  // Whether to test various input presets. Note use of "-ez"
> --ez use_input_devices  {boolean}  // Whether to test various input devices. Note use of "-ez"
> --ez use_output_devices {boolean}  // Whether to test various output devices. Note use of "-ez"
> --ei single_test_index  {testId}   // Index for testing one specific test
I've updated the markdown file in the docs directory since we have added a new test of tests 
Fixes #1294
> (OboeTester) Create automatic data paths tests

- src/common/QuirksManager.cpp
MMAP not supported before Q.
But some phones tried to use it.
Fixes #1121
> Quirk: disable MMAP on SDM8150

- samples/LiveEffect/README.md
- samples/LiveEffect/src/main/java/com/google/oboe/samples/liveEffect/MainActivity.java
- samples/LiveEffect/src/main/res/layout-v21/activity_main.xml
- samples/LiveEffect/src/main/res/layout/activity_main.xml
Fixes #1419
Also slightly restructured the UI to have API selection on top. See how the playback/recording device selection is now disabled when OpenES SL is selected.
> (LiveEffect) Disable setting playback or recording devices with OpenSL ES

- include/oboe/Version.h
To distinguish patches since 1.6.1 release.
Fixes #1433
> Bump Oboe version to 1.6.2

- samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/MainActivity.java
Fixes #909
This PR adds an ability to toggle Bluetooth SCO when it is actually set. We should also update the Wiki to document Bluetooth after this PR is submitted.
Tested on Pixel 4a and Pixel Series A.
Verified that SCO does not play correctly before this change.
Toggled between SCO and A2DP and verified that the sound changes with this change.
> (HelloOboe) Add Bluetooth SCO sample

- include/oboe/AudioStream.h
Also calculateLatencyMillis().
> Recommend not calling getTimestamp() from callback

- src/aaudio/AudioStreamAAudio.cpp
- tests/CMakeLists.txt
- tests/UnitTestRunner/app/build.gradle
- tests/UnitTestRunner/app/src/main/AndroidManifest.xml
- tests/UnitTestRunner/app/src/main/java/com/google/oboe/tests/unittestrunner/MainActivity.java
- tests/UnitTestRunner/build.gradle
- tests/UnitTestRunner/gradle/wrapper/gradle-wrapper.properties
- tests/testStreamOpen.cpp
- tests/testStreamStop.cpp
- tests/testStreamStopWrite.cpp
This PR fixes an issue where AAudio segfaults if the stream is closed while read or write occurs. The main work done here is a 2 line change adding shared locks for read and write. This is relatively safe as these locks are only used as exclusive for close(), which should wait for all operations to finish in the first place.
I've updated a few things related to unit tests.
1. The unit tests to use a newer version of gradle.
2. I added tests to account to test the new AAudio shared read/write locks.
3. Unit tests wouldn't run for devices built with hardware sanitizer, so I've added a check.
Fixes #1484
> AAudio: add locks around reading and writing

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
- apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.h
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DoubleStatistics.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
Compare with measured acoustic latency.
This will allow us to measure the accuracy of
the timestamps.
The reported value is "timestamp.latency.msec".
Fixes #1498
> Measure timestamp latency for full duplex stream.

- src/flowgraph/resampler/PolyphaseResampler.cpp
- src/flowgraph/resampler/SincResampler.cpp
- src/flowgraph/resampler/SincResamplerStereo.cpp
A compilation error occurs on latest LLVM libcxx (tested on https://github.com/llvm/llvm-project/commit/6e2c6c9def394c79a65bb216ac3d5261d39cc960) due to the C++ stdlib header `<algorithm>` being a transitive dependency that is no longer included on the latest LLVM libcxx (as of https://reviews.llvm.org/D119667), this causes breakage for instances of `std::find`/`std::find_if` as they cannot be resolved. This PR explicitly includes the `<algorithm>` header wherever necessary to compile without errors but it is generally a good practice to avoid transitive dependencies.
> Include <algorithm> explicitly

- apps/OboeTester/app/build.gradle
- include/oboe/Definitions.h
- src/opensles/EngineOpenSLES.cpp
Link with slCreateEngine using dlsym().
OpenSL ES is deprecated in SDK >= 30.
Fixes #1530
> opensles: use dlsym() to link

- src/opensles/AudioStreamOpenSLES.cpp
Fixes #1536
OboeTester output streams that set Unspecified works as intended now.
> OpenSL ES: Set usages if unspecified

- apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
Disambiguate correlation and confidence.
Display correlation in Activity.
Make getMeasuredConfidence() public.
> OboeTester: cleanup latency test

- src/flowgraph/FlowgraphUtilities.h
- tests/testFlowgraph.cpp
Fixes #1539
Note the new test passes both before and after the clamp32FromFloat code change.
> Flowgraph: Use INT32_MIN for clamp32FromFloat()

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioStreamBuffered.cpp
- src/opensles/AudioStreamOpenSLES.cpp
There were resource leaks if the open failed.
So now it calls close() internally if open fails.
Fixes #1541
> opensles: clean up after failed open

- tests/testStreamOpen.cpp
The TODO said they were hanging. But I think that was caused by
a native crash in AAudio related to callback size.
See #778
> tests: reenable crashing tests

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioStreamBase.java
> OboeTester: remove extra \n in xRun#

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfiguration.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_test_output.xml
- apps/OboeTester/app/src/main/res/layout/stream_config.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
- include/oboe/AudioStreamBase.h
- include/oboe/AudioStreamBuilder.h
- include/oboe/Definitions.h
- include/oboe/Utilities.h
- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
- src/aaudio/AudioStreamAAudio.cpp
- src/common/Utilities.cpp
For AAudio, channel mask support was added in API 32. In this change,
channel mask support is added in Oboe for API 32.
Fixes #1409.
> Add channel mask support for API 32.

- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
Fixes #1567
If processBufferCallback() is called after setPlayState_l(SL_PLAYSTATE_PLAYING), there could be cases where onAudioReady() is called from two threads.
We should not release the lock just for processBufferCallback(), so there is a minor refactor here. processBufferCallback() now returns a bool and that bool is used to determine whether requestStop_l() should be called.
> OpenSL ES: Call processBufferCallback before setting the playstate to playing

- .github/workflows/build-ci.yml
CodeQL Action V1 will be [deprecated](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/) in December 2022. We are updating to V2 in this PR.
> Workflow: Update to the newest version of CodeQL

- src/opensles/AudioStreamBuffered.cpp
- tests/testStreamOpen.cpp
Fixes #1581
New test fails on all devices on all Android versions before tests.
This test passes after the change.
> OpenSL ES: Fix getBufferSizeInFrames for non-callback OpenSL ES

- apps/fxlab/app/build.gradle
- apps/fxlab/app/src/main/AndroidManifest.xml
- apps/fxlab/app/src/main/java/com/mobileer/androidfxlab/EffectsAdapter.kt
- apps/fxlab/build.gradle
- apps/fxlab/gradle/wrapper/gradle-wrapper.properties
This PR fixes two bugs relating to fxlab settings not being persistent.
1. Using effectList[index].paramValues[counter] instead of param.defaultValue allows UI to restore on placement swaps.
2. Adding android:configChanges="orientation|screenSize|keyboardHidden" allows effects to stay and audio engine to not be restarted when screen is rotated.
Fixes #1120
Fixes #834
> fxlab: Restore effect UI when placement changes and on screen rotation

- include/oboe/StabilizedCallback.h
Fixes #1585
From https://android-review.googlesource.com/c/platform/external/oboe/+/2170113
> Add riscv definition to StabilizedCallback.h

- src/common/QuirksManager.cpp
- src/common/QuirksManager.h
Fixes #201
Fixes #1589
I don't have a Vivo to test this.
I did test Oboe workarounds in OboeTester on a Pixel phone.
> Quirks: Include Vivo and check for Oboe workaround flag

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
Fixes #1428
I tested that changes work as expected on Pixel 6 after changing mmap settings.
> OboeTester: Hide mmap settings if not enabled after stream stop.

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
Was using 1/2 capacity, which is sometimes only one burst.
Fixes #1560
> OboeTester: use 2 burst min for glitch test

- include/oboe/AudioStream.h
- include/oboe/Version.h
- src/aaudio/AudioStreamAAudio.cpp
- src/aaudio/AudioStreamAAudio.h
- src/common/AudioStream.cpp
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
- tests/testStreamClosedMethods.cpp
Add: AudioStream::setDelayBeforeCloseMillis(delay)
This can be used to avoid use-after-free bugs
cause by callbacks running when close is called.
Fixes #1500
> Add API to set sleep time before close.

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
Size from AudioManager was being ignored.
Fixes #1598
> OboeTester: set default frames per burst

- apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
Instead of always reading from the first channel, we should read from the channel intended by the test with setInputChannel().
This code does not cause any issues currently as only setInputChannel(0) is ever called. However, we should still change fix this.
> OboeTester: Glitch Activity should read from intended input channel

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
- apps/OboeTester/docs/AutomatedTesting.md
This PR adds instructions for channel mask automated testing.
This PR also makes two changes to the intents:
1. Split KEY_CHANNEL_MASK to KEY_IN_CHANNEL_MASK and KEY_OUT_CHANNEL_MASK. This way input and output channel masks can be requested independently.
2. Change quadside and 5.1side to quadSide and 5.1Side. This allows for a consistent capitalization between channel mask strings.
3. For camelCase strings, check for camelCase or lowercase. For example, both quadSide and quadside will work.
> OboeTester: Add instructions for channel mask automated testing

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/EchoActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDisconnectActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestOutputActivityBase.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestPlugLatencyActivity.java
- apps/OboeTester/app/src/main/res/layout/stream_config.xml
Currently, java audio effects are neither stable nor easily testable. This PR adds some basic audio effects to audio stream configs. This way, audio effects can be added to most existing tests.
Fixes #1527
Below are some screenshots:
> OboeTester: Add ability to add audio effects from stream configs

- src/opensles/AudioInputStreamOpenSLES.cpp
This PR does 2 things:
1. Check buffer depth before enqueuing for input streams. This is the input equivalent of #625.
2. Queue an callback buffer before setting record state to recording. This is the input equivalent of #1570.
Fixes #1431
> OpenSL ES: Check zero buffer depth and enqueue before setRecordState for input streams

- src/flowgraph/resampler/MultiChannelResampler.cpp
- src/flowgraph/resampler/SincResampler.cpp
- src/flowgraph/resampler/SincResamplerStereo.cpp
- tests/CMakeLists.txt
- tests/testFlowgraph.cpp
- tests/testResampler.cpp
Converting from 11025 to 48000 with Best quality had a strong glitch. Added guard row to Coefficients table for interpolation.
Fixes #1622
> resampler fix glitch in some configurations

- apps/OboeTester/app/src/main/cpp/TestErrorCallback.cpp
- apps/OboeTester/app/src/main/cpp/TestErrorCallback.h
- include/oboe/AudioStreamBase.h
- include/oboe/AudioStreamBuilder.h
Pass data and error callbacks to builder using a shared_ptr. Deprecate methods that pass raw pointers.
This is to avoid the callback getting deleted while the error callback is active.
Fixes #1603
> oboe: use shared_ptr for callbacks

- include/oboe/AudioStreamBuilder.h
setFormatConversionAllowed was changed to match code in https://github.com/google/oboe/commit/1fd49e2f1d0980995b61cb33f5ef0cbe0eae6963. We should do the same for setChannelConversionAllowed
Fixes #712
> Match setChannelConversionAllowed comment to code

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestPlugLatencyActivity.java
I tested with a 3.5mm headset and this now shows one sink and one source
> OboeTester: Log whether an added device is a sink or source in TestPlugLatencyActivity

- samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp
- samples/hello-oboe/src/main/cpp/HelloOboeEngine.h
- samples/hello-oboe/src/main/cpp/jni_bridge.cpp
- samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/BackgroundRunner.java
- samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/MainActivity.java
- samples/hello-oboe/src/main/java/com/google/oboe/samples/hellooboe/PlaybackEngine.java
- samples/shared/DefaultDataCallback.h
Call audio in background to prevent ANRs.
If AudioServer has crashed it can cause the UI thread to time out.
Fixes #960
Fixes #1538
> Add BackgroundRunner to HelloOboe

- apps/OboeTester/app/build.gradle
- include/oboe/AudioStream.h
- include/oboe/Version.h
- src/common/AudioStream.cpp
Clip against BufferCapacity minus BurstSize.
Also bump Oboe to 1.7.1 and OboeTester to  2.3.6.
Fixes #1701
> oboe: clip waitForAvailableFrames

- apps/OboeTester/app/build.gradle
- include/oboe/Version.h
- src/aaudio/AudioStreamAAudio.cpp
AAudio could sometimes return a positive number (1) as an error code. That was confusing to apps like OboeTester, which often look for (result < 0).
The fix is to coerce these bogus error codes to ErrorInternal.
Bump Oboe to 1.7.2 and OboeTester to 2.3.7.
> Coerce positive error from open() to negative code

- .github/workflows/build-ci.yml
- .github/workflows/update-docs.yml
When running the presubmit workflow, there are two warnings.
1. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. This is an artifact of using an old Java version.
3. https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. This is an artifact of using actions/checkout@v2.
> Upgrade build CI

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
In case AAudio returns a positive error by mistake.
Fixes #1706
> OboeTester: check for (result != 0)

- src/aaudio/AAudioExtensions.h
It should be accessed through AAudioExtensions::getInstance().
Fixes #1709
> oboe: make AAudioExtensions() private for singleton

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioQueryTools.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java
Build.VERSION.MEDIA_PERFORMANCE_CLASS is not defined before Android S.
Fixes #1738
> OboeTester: Fix Device Report crash before Android S

- samples/drumthumper/README.md
- samples/drumthumper/src/main/cpp/DrumPlayerJNI.cpp
- samples/drumthumper/src/main/kotlin/com/plausibleaudio/drumthumper/DrumPlayer.kt
- samples/drumthumper/src/main/kotlin/com/plausibleaudio/drumthumper/DrumThumperActivity.kt
- samples/iolib/src/main/cpp/player/OneShotSampleSource.cpp
- samples/iolib/src/main/cpp/player/SampleBuffer.cpp
- samples/iolib/src/main/cpp/player/SampleBuffer.h
- samples/iolib/src/main/cpp/player/SampleSource.h
#1719 fixed made stereo content not crash but it was not actually being read. It added stereo support to the wav reader but not to the files that used the content.
This PR reads the stereo data in OneShotSampleSource.
Because stereo is now supported, some bandage code that checks the channel count has been removed.
Fixes #1735
> DrumThumper: Support stereo

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
`onStopAudioTest()` calls `onTestFinished()` which updates the share UI. However, it reset it right after with `mShareButton.setEnabled(false);`. This change removes the duplicate work.
Fixes #1752
> OboeTester: Fix manual glitch activity sharing

- src/aaudio/AudioStreamAAudio.h
Fixed some misspelled and misplaced declarations.
Fixes #1761
> oboe: remove getMDelayBeforeCloseMillis from header

- apps/OboeTester/app/CMakeLists.txt
- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/cpp/TestRoutingCrash.cpp
- apps/OboeTester/app/src/main/cpp/TestRoutingCrash.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExtraTestsActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestRouteDuringCallbackActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_extra_tests.xml
- apps/OboeTester/app/src/main/res/layout/activity_routing_crash.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
This test tries to trigger a routing change
while long duration callbacks are playing.
This can cause the callback to write into a dead buffer and cause a SIGSEGV.
See b/274815060
> oboetester: try to repro routing crash

- apps/OboeTester/app/src/main/cpp/TestRoutingCrash.cpp
- apps/OboeTester/app/src/main/cpp/TestRoutingCrash.h
- apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExtraTestsActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestRouteDuringCallbackActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_routing_crash.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
Show loopcount on screen.
Simplify sleep calculation to simulate a workload proportional to the numFrames.
Add more comments and improve instructions.
> OboeTester: add Input to Routing Stress test

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceSpinner.java
- apps/OboeTester/app/src/main/java/com/mobileer/audio_device/CommunicationDeviceSpinner.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/FastButton.java
When making custom spinners and text views, we should use [AppCompatSpinner](https://developer.android.com/reference/kotlin/androidx/appcompat/widget/AppCompatSpinner) and [AppCompatTextView](https://developer.android.com/reference/kotlin/androidx/appcompat/widget/AppCompatTextView).
See the links to the new files. These bring new features to old versions of Android.
> OboeTester: Use AppCompatSpinner and AppCompatTextView

- apps/OboeTester/app/src/main/cpp/FormatConverterBox.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioStreamBase.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfiguration.java
- apps/OboeTester/app/src/main/res/values/strings.xml
- include/oboe/AudioStreamBase.h
- include/oboe/Definitions.h
- src/common/QuirksManager.cpp
- src/common/Utilities.cpp
- src/opensles/OpenSLESUtilities.cpp
> Add IEC61937 for API 34 

- apps/OboeTester/app/src/main/res/layout/merge_audio_common.xml
After PR #1755, on some devices, the word "RELEASE" takes too much space and spans multiple columns. The fix here is to make the font size a bit smaller.
sp is more dynamic compared to using dp
> OboeTester: Make font sizes a bit smaller for buttons

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
InputAnalyzer creates a buffer based on the burst size for callbacks.
This did not account for the fact that the user can manually override the callback size.
Fixes b/278942008
> OboeTester: check for callback size in InputAnalyzer

- apps/OboeTester/app/src/main/cpp/FormatConverterBox.cpp
- apps/OboeTester/app/src/main/cpp/FormatConverterBox.h
Catch conversions larger than allocated buffer size.
> Add assert() in FormatConverterBox

- apps/OboeTester/app/src/main/res/values/strings.xml
So users know what to expect and can detect regressions.
> OboeTester: Routing Stress comment, fixed in U

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BufferSizeView.java
- apps/OboeTester/app/src/main/res/layout/buffer_size_view.xml
If you uncheck all the individual radio buttons
then they stop working properly.
So you have to uncheck the RadioGroup.
Internal bug: b/280421942
> OboeTester: fix buffer size radio button

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
Skip configureAfterOpen() is open failed.
Fixes #1809
> OboeTester: fix crash if open failed

- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
Stop sniffer when onStop() called for Activity.
The sniffer was being left running the background. That was causing the workload to go up and down.
Fixes #1817
> OboeTester: stop CPU Load sniffer

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
when running a test driven by Intents.
Fixes #1826
> OboeTester: fix hang on devices without MMAP

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AnalyzerActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExternalFileWriter.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfiguration.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
- apps/OboeTester/docs/AutomatedTesting.md
Also change where the results files is stores.
No longer requires permissions but the path name is longer!
See apps/OboeTester/docs/AutomatedTesting.md
> OboeTester: add out_usage to automated testing

- tests/testResampler.cpp
The resampler was not properly pulled for the last few output samples so they were stuck in the resampler. By pulling the remaining samples, we can reenable higher sample rates.
I adjusted some values of constants to account for these changes.
Fixes #1822
> Unit Tests: reenable high sample rates

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
`streamContext.tester = AudioInputTester.getInstance();` is already executed at the start of the function
> remove unecessary streamContext.tester assignement

- apps/OboeTester/app/src/main/cpp/AudioStreamGateway.cpp
- apps/OboeTester/app/src/main/cpp/InputStreamCallbackAnalyzer.cpp
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
It was ignoring the menu setting when not using callbacks.
See #1829
> OboeTester: fix hang msec menu when no callbacks

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
A change to the Volume ramp caused a regression.
Fixes #1857
> OboeTester: fix crash in Tap-to-tone

- samples/SoundBoard/src/main/kotlin/com/google/oboe/samples/soundboard/MainActivity.kt
- samples/SoundBoard/src/main/kotlin/com/google/oboe/samples/soundboard/MusicTileView.kt
View.onConfigurationChanged() gets called whenever the window size changes. Since the Activity handles the size of the tiles in the app, an interface is added so the activity knows when to recreate the tiles.
Fixes #1867
> Soundboard: support multi-display devices

- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
> OboeTester: waitForStateChange should not be called in disconnect

- apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceInfoConverter.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
Remove earpiece tests because they are flakey.
Show more info when open fails.
Display channel masks in hex format.
Fixes #1866
> OboeTester: Data Paths cleanup, remove earpiece

- apps/OboeTester/app/src/main/res/values/strings.xml
For smaller screens, the release button is taking multiple lines.
> OboeTester: Shorten Release string

- samples/SoundBoard/src/main/kotlin/com/google/oboe/samples/soundboard/MainActivity.kt
When starting from G3, there are too many notes you can't hit if the output is a 5x5 grid.
> soundboard: Increase dimensions

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDisconnectActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_test_disconnect.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
Some peripherals have no mic so the INPUT test fails. Now there will be a message explaining why.
Also add checkboxes for disabling INPUT or OUTPUT tests.
Avoid asking user to plug in a headset when it is already plugged in.
Fixes #1045
> OboeTester: TEST DISCONNECT checks for mic on headset

- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
> OboeTester: Stop using get_nprocs()

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDisconnectActivity.java
- src/common/FilterAudioStream.h
- tests/testStreamOpen.cpp
sharingMode and the hardware formats were not getting copied.
It was noticed in OboeTester.
The test specs for TEST DISCONNECT were made more rational.
Also a unit test was added to catch the oboe bug.
Fixes #1897
> oboe: copy more parameters in FilterAudioStream

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioStreamBase.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
Show CPU migrations.
Fix clearing of CPU affinity.
Disable drawing during the benchmarking phase so it will converge.
> OboeTester: improve CPU LOAD test

- apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
- apps/OboeTester/app/src/main/res/values/strings.xml
* Reduce tolerance for glitches.
* Ask user to plugin loopback adapter and turn up volume. 
* Print peak.amplitude and sine.amplitude in report. Warn if peak.amplitude too low.
* Don't compare with other passed tests if none passed. 
* Fix SNR calculation. Was always 0.0.
Fixes #1902
> OboeTester: AUTO GLITCH improvements

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/CommunicationDeviceView.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/EchoActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/GlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/NativeSniffer.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
Call getCommunicationsDevice() periodically and show the result.
This can be used to detect the "grace period" after calling setCommunicationDevice().
Also cleaned up NativeSniffer.
> OboeTester: update the current communications device

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_data_paths.xml
- apps/OboeTester/docs/AutomatedTesting.md
Currently, the data paths test only plays output channel masks explicitly declared in AudioDeviceInfo.
AudioFlinger handles downmixing for extra channels. Thus, we can actually test that downmixing works for channel masks that the device does not explicitly support.
This PR changes output configs to an arbitrary set of channel masks (mono, stereo, 2.1, 7.1.4) with an checkbox to test all supported channel masks.
Fixes #1912
> OboeTester: Test downmixing with data paths test 

- samples/SoundBoard/src/main/cpp/Synth.h
- samples/shared/Mixer.h
This PR fixes some issues with potential overflow of buffers.
1. Mixer buffer in Mixer.h could be too small if frame size is large. Fix here is to use std::unique_ptr<float[]> instead of a raw array. Mixer.h is used by MegaDrone, Soundboard, and RhythmGame.
2. If the number of tracks goes over 100 in Mixer.h, there will be a buffer overflow. Fix here is to use std::vector<IRenderableAudio*> instead of an std::array.
3. If the number of tracks goes over 100 in Synth.h, there will be a buffer overflow. Fix here is to use std::unique_ptr<SynthSound[]> instead of an std::array.
Fixes #1921
> Samples: Remove some fixed size constants

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestColdStartLatencyActivity.java
- apps/fxlab/app/build.gradle
- samples/LiveEffect/build.gradle
- samples/MegaDrone/build.gradle
- samples/RhythmGame/build.gradle
- samples/SoundBoard/build.gradle
- samples/audio-device/build.gradle
- samples/drumthumper/build.gradle
- samples/hello-oboe/build.gradle
- samples/iolib/build.gradle
- samples/parselib/build.gradle
- tests/UnitTestRunner/app/build.gradle
> Update to Android 14

- apps/OboeTester/app/src/main/cpp/InterpolatingDelayLine.cpp
- apps/OboeTester/app/src/main/cpp/InterpolatingDelayLine.h
- apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/ManchesterEncoder.h
The latncy analysis was too slow on lower end devices. This use a rough pass to find an approximate latency.
Then it does a fine grained analysis in a small window around the approximate peak to find the exact value.
Fixes #1939
> OboeTester: speed up latency analysis by >100X

- src/opensles/AudioOutputStreamOpenSLES.cpp
Was using SL_ANDROID_STREAM_NOTIFICATION
should be SL_ANDROID_STREAM_RING
Fixes #1945
> opensl: fix stream type for ringtone

- include/oboe/AudioStreamBuilder.h
- src/common/AudioStreamBuilder.cpp
Call an internal method that does not print the warning.
Fixes #1949
> Prevent deprecation warning for shared openStream() call

- apps/OboeTester/app/build.gradle
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDisconnectActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_test_disconnect.xml
With listening to USB device de/attach event, disconnect test can well sync on the peripherals plug state.
> Listen to USB device de/attach event.

- samples/iolib/src/main/cpp/player/SimpleMultiPlayer.h
Fixed a small typo. Removed 3 instances of the letter `I`.
> Fixed typo. Renamed *SIMIPLE* => *SIMPLE* by removing the letter `I`.

- src/aaudio/AAudioExtensions.h
If policy is Unspecified then return isMMapSupported.
Fixes #1967
> Fix isMMapEnabled()

- apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ManualGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_data_paths.xml
- apps/OboeTester/app/src/main/res/layout/activity_manual_glitches.xml
- apps/OboeTester/app/src/main/res/layout/activity_test_input.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
Support Data Paths testing for USB and wired headsets.
Add channel selectors for Manual Glitch Activity so we can test individual loopback paths.
Improve display of test results.
Prevent mismatching datapath devices such as mic and USB headphones.
This is WIP.
We still need to convert all the paths to the new style.
And we need more check boxes that reflect the test areas.
> Improve Data Paths and Glitch tests

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
The previous channel count/mask selection is currently ignored correctly but the UI does not indicate that.
This PR explicitly updates the UI.
Fixes #1944
> OboeTester: Override previous channel mask/count selection

- apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/DataPathAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/WaveformView.java
- apps/OboeTester/app/src/main/res/layout/activity_data_paths.xml
Set phase calculation as invalid when magnitude is low. Some tests has phaseJitter=0.
Also some tests had very high phaseJitter and
should have failed. So I lower the max allowable jitter.
> OboeTester: Fix problem with phaseJitter=0 in DataPaths

- samples/parselib/src/main/cpp/wav/AudioEncoding.h
- samples/parselib/src/main/cpp/wav/WavStreamReader.cpp
24 bit and 32 bit support was added in #1221. I tested that they work with DrumThumper.
This PR now declares that those audio encodings are valid.
> Samples: Add 24 bit and 32 bit support for parsing wav files

- src/flowgraph/SampleRateConverter.cpp
- src/flowgraph/SampleRateConverter.h
The SampleRateConverter curser was initialized to -1 causing a read before the array bounds.
Now it is initialized to zero.
Also initialize mInputCallCount to kInitialCallCount.
This code is from a change in AAudio, ag/27104819
Fixes #2005
> Fix out-of-bounds read in SRC

- tests/testFullDuplexStream.cpp
Fixes #2008
This is a newish test and we want to make the test a bit less sensitive to start conditions.
> Unit Tests: Make full duplex tests less sensitive

- apps/OboeTester/app/src/main/cpp/FullDuplexStreamWithConversion.cpp
Fixed calculation of required buffer size for input format conversion.
Fixes #2011
> OboeTester: fix assert in FormatConverterBox

- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioInputStreamOpenSLES.h
- src/opensles/AudioOutputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.h
- src/opensles/AudioStreamOpenSLES.cpp
- src/opensles/AudioStreamOpenSLES.h
- src/opensles/EngineOpenSLES.cpp
- src/opensles/EngineOpenSLES.h
- src/opensles/OutputMixerOpenSLES.h
Use dlsym() to find the address of symbols like SL_IID_PLAY. This allows Oboe to be run on a device that does not have "libOpenSLES.so".
This fixes b/337360630
> oboe: remove OpenSL ES direct links

- docs/FullGuide.md
Hey Oboe folks 👋
My company has been using Oboe to build a realtime music learning app where simultaneously a video of the band is played whilst the microphone listens to the user's playing of their instrument. We use Oboe for both the audio input (recording of the user playing) and output (playback of the band, part of a low-level custom player using FFmpeg and Oboe for the audio backend). As you can imagine having precise synchronisation between the playback and recording in our setup is paramount as we analyse the user's rhythm and pitch after they have performed.
After doing a deep dive into some poor scores I noticed that there was a large amount of additional and device dependant latency in our recordings. Initially, I thought this was an issue with our playback (asset encoding or …
> docs: Update guide to note additional latency with default sample rate conversion quality

- docs/FullGuide.md
- include/oboe/AudioStreamBase.h
- tests/testStreamOpen.cpp
> Set SampleRateConversionQuality as Medium by default

- include/oboe/AudioStream.h
- src/aaudio/AudioStreamAAudio.cpp
- src/common/AudioStream.cpp
- src/common/AudioStreamBuilder.cpp
- src/common/FilterAudioStream.h
This is used when Oboe does sample rate conversion. Or format or channel count conversion.
It used to use a raw pointer, which could cause crashes.
Fixes #2035
> Use shared_ptr in FilterAudioStream

- apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
- src/common/AudioStream.cpp
This would have helped us catch a service bug sooner.
> oboe: log warning if start times out

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- include/oboe/FullDuplexStream.h
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp
- samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
- tests/testFullDuplexStream.cpp
- tests/testReturnStop.cpp
- tests/testStreamFramesProcessed.cpp
- tests/testStreamOpen.cpp
> FullDuplexStream: deprecate raw pointers when setting streams

- apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
- apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.h
This prevents underruns when doing sample rate conversion.
Fixes #2046
> OboeTester: DataPaths input margin increased from 1 to 3

- apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.cpp
- apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
This will help with debugging.
Fixes #2044
> OboeTester: save a WAVE file when DataPaths test fails

- apps/OboeTester/app/CMakeLists.txt
- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/cpp/TestRapidCycle.cpp
- apps/OboeTester/app/src/main/cpp/TestRapidCycle.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExtraTestsActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestRapidCycleActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_extra_tests.xml
- apps/OboeTester/app/src/main/res/layout/activity_rapid_cycle.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
- src/opensles/AudioOutputStreamOpenSLES.cpp
This was an attempt to reproduce b/348615156
b/348615156 | P2 | [Oboe/OpenSLES] Deadlock is caused when close function is called immediately after stream playback.
> OboeTester: add a Rapid Cycle test

- docs/AppsUsingOboe.md
- docs/README.md
`docs/AppsUsingOboe.md` just links to https://github.com/google/oboe/wiki/AppsUsingOboe. We should just get rid of the former.
> Docs: Get rid of docs/AppsUsingOboe.md

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioQueryTools.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DeviceReportActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_main.xml
Because the fingerprint may no longer have a timestamp!
b/348672935 | P2 | ro.build.fingerprint has 00000000.000000 instead of the date
> OboeTester: display ro.build.date in MainActivity

- samples/LiveEffect/src/main/java/com/google/oboe/samples/liveEffect/MainActivity.java
Since duplex streams are often used in the background, we should let LiveEffect run in the background.
Some users have trouble with FullDuplexStream in the background (#2062) so we should have a sample to point them to.
> LiveEffect: Run in background

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
Go up by a minor third or a perfect fourth just intoned interval.
Fixes #2066
> OboeTester: use lower pitches for high channel counts

- apps/OboeTester/app/src/main/cpp/FullDuplexAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/DataPathAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/GlitchAnalyzer.h
This will prevent glitches caused by the number of input and output frames being different in the full duplex callback.
Fixes #2068
> OboeTester: add sine wave oscillator as a reference for input

- apps/OboeTester/app/src/main/AndroidManifest.xml
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioForegroundService.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
- apps/OboeTester/app/src/main/res/drawable/ic_notification.xml
- apps/OboeTester/app/src/main/res/layout/activity_main.xml
> OboeTester: Create foreground service

- src/opensles/AudioStreamOpenSLES.cpp
There were some missing parameters for OpenSL ES warnings.
> OpenSL ES: Update warning logs for invalid params

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
- apps/OboeTester/app/src/main/res/layout/stream_config.xml
It's good to know what the default device id is for AAudio and that the device id is ignored for OpenSL ES.
> OboeTester: Display Actual Device Id

- tests/testStreamFramesProcessed.cpp
It seems that we were missing some tests where no sample rate conversion is used for sample rates like 8000. This PR adds another param to TestStreamFrameProcessed to help test this case.
> Unit Tests: Test no sample rate conversion in TestStreamFrameProcessed

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
Handle any combination of USB Headset or Device.
> OboeTester Data Paths handle mix of USB

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
Do not test more USB device output channels than there are inputs.
Fixes #2087
> OboeTester: limit number of channels tested in Data Paths

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
- apps/OboeTester/app/src/main/res/layout/stream_config.xml
Also add NoiseSuppressor
For #2090
> OboeTester: show default AEC status

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioForegroundService.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseOboeTesterActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/ExtraTestsActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
Currently, the OboeTester foreground service declares that its service types are both media playback and microphone, regardless of what activity is used.
Test Input and Test Output should be different service types when using a foreground service. This PR makes this change. This allows us to undo an confusing commit #2100.
Fixes #2105
> OboeTester: Foreground service type should depend on activity type

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
Add options to enable ADPF and scrolling graphics
Fixes #2103
> OboeTester: add Intent to automate CPU Load test

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/RoundTripLatencyActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestInputActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_rt_latency.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
This can be used to detect errors in the DSP MMAP position timestamps
used by the AAudio IsochronousClockModel.
If the DSP position is off then it can cause a discontinuity in round-trip latency as a function of buffer size.
So we change the buffer size and look for the discontinuity.
> OboeTester: measure latency with varying buffer sizes to detect MMAP errors

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/util/WaveFileWriter.cpp
- apps/OboeTester/app/src/main/cpp/util/WaveFileWriter.h
- src/opensles/AudioInputStreamOpenSLES.cpp
- src/opensles/AudioOutputStreamOpenSLES.cpp
> OboeTester: write WAV chunk sizes when recording

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/NativeEngine.java
- apps/OboeTester/app/src/main/res/layout/activity_dynamic_workload.xml
- apps/OboeTester/docs/AutomatedTesting.md
- include/oboe/AudioStream.h
- src/aaudio/AudioStreamAAudio.h
- src/common/AdpfWrapper.cpp
- src/common/AdpfWrapper.h
Give ADPF advance warning when the application workload changes. This can reduce glitching when the workload increases suddenly. It works by estimating what the callback duration will be and then reporting that to ADPF as if it had already happened.
> Oboe: add reportWorkload()

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
We were seeing some of the sample rate conversion tests failing on Pixel 7. The signal was OK but the cold start latency was a bit slow. So the test was timing out.
See b/384751468
> Incerase Data Paths duration from 3 to 4

- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp
- apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.h
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
If the workload is set in the middle of onAudioReady(), the new workload can be used for the synth before audioStream->reportWorkload() is called for this workload.
The fix here is to use an atomic variable and the same workload throughout the function.
> OboeTester: Fix race condition with setWorkload in Dynamic Workload Activity

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedTestRunner.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
Was +1 because it was being calculated based on variables instead of direct counting.
See b/375050058
> OboeTester: fix skip count display near top of screen for Data Paths test

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/NativeSniffer.java
When stopSniffer() is called, there are no more updates for the sniffer because mEnabled is set to false. This is clearly a bug.
The proposed change here is to add a new variable called mEnableFinalUpdate which will handle the final update.
> OboeTester: Let the final update of NativeSniffer actually update

- src/common/AdpfWrapper.cpp
There doesn't seem to be any upsides in using CLOCK_REALTIME over CLOCK_MONOTONIC in AdpfWrapper.cpp. Since the rest of the Oboe codebase uses CLOCK_MONOTONIC, we should also use it here.
> AdpfWrapper: Use CLOCK_MONOTONIC instead of CLOCK_REALTIME

- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- src/common/AdpfWrapper.cpp
- src/common/AdpfWrapper.h
- src/common/Trace.cpp
- src/common/Trace.h
With ATrace, we can profile the time between callbacks for the workload. Perfetto provides a nice UI to see this callback time in comparison to other metrics like CPU usage and the ADPF session batch size.
Instructions:
1. Start the perfetto trace on your computer with `adb shell -t perfetto audio sched freq power hal idle binder_driver ss --time 20s --out /data/misc/perfetto-traces/test123.pf --app com.mobileer.oboetester`
2. Pull the perfetto trace from the android phone to your computer `adb pull /data/misc/perfetto-traces/test123.pf localfile.pf`
3. Open the new file in ui.perfetto.dev
Note that ATrace_setCounter() is only supported on Android level 29 and above and ATrace_isEnabled() is enabled only when the perfetto command is run from adb shell.
> AdpfWrapper: Add trace for actualDurationNanos

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/DynamicWorkloadActivity.java
- apps/OboeTester/app/src/main/res/layout/activity_dynamic_workload.xml
See https://developer.android.com/reference/android/view/Window.html#setSustainedPerformanceMode(boolean)
> OboeTester: Add sustained perf to Dynamic CPU Load test

- apps/OboeTester/app/src/main/cpp/MultiChannelRecording.h
- apps/OboeTester/app/src/main/cpp/TestErrorCallback.h
- apps/OboeTester/app/src/main/cpp/analyzer/LatencyAnalyzer.h
- apps/OboeTester/app/src/main/cpp/analyzer/PseudoRandom.h
- apps/OboeTester/app/src/main/cpp/analyzer/RoundedManchesterEncoder.h
- apps/OboeTester/app/src/main/cpp/synth/SawtoothOscillatorDPW.h
- apps/OboeTester/app/src/main/cpp/synth/SineOscillator.h
- apps/OboeTester/app/src/main/cpp/synth/SquareOscillatorDPW.h
Add some missing includes in the OboeTester code.
This PR includes `common/OboeDebug.h` which there was precedent for, but perhaps should not be part of the OboeTester app, unless `OboeDebug.h` is moved to the `includes` directory for Oboe.
> OboeTester: Add missing includes.

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
This way combining channels will not result in overflows when downmixing
> OboeTester: divide oscillator amplitude by channel count

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/OboeAudioStream.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfiguration.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
- apps/OboeTester/app/src/main/res/layout/stream_config.xml
- apps/OboeTester/app/src/main/res/values/strings.xml
> OboeTester: Add SpatializationBehavior

- .github/workflows/build-ci.yml
- .github/workflows/update-docs.yml
Our workflows are currently broken due to missing write permissions. See https://github.com/google/oboe/actions/runs/13594935708/job/38009571205 as one example
> Update workflows with write permissions

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java
- apps/OboeTester/app/src/main/res/layout/stream_config.xml
Adding an extra checkbox for session id so it can be set independently of whether effects are used. Enabling effects always allocates the session id but not the other way around.
> OboeTester: Add separate session id checkbox

- include/oboe/AudioStream.h
These parameters are not used so certain compliers give warnings. We should not use something like /* appWorkload */  because these are virtual functions
> AudioStream: Add std::ignore for unused parameters

- src/aaudio/AAudioLoader.cpp
- src/aaudio/AAudioLoader.h
This makes it so when Oboe is used without the NDK, symbols are not defined explicitly. This does not affect 99% of use cases.
> AAudioLoader: Add explicit checks that NDK is used

- include/oboe/Oboe.h
Fixes #2179
Docs at https://google.github.io/oboe/
> Update Oboe.h to remove missing link

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp
Not needed as mSinkMemoryDirect is created in this function
> OboeTester: remove extra mSinkMemoryDirect nullptr check

- apps/OboeTester/app/src/main/cpp/NativeAudioContext.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AnalyzerActivity.java
I tried to prevent getResetCount() from being called when the stream is not ready. But it was hard to track down the offending call.
So I just prevented the NULL crash.
I then added a dump of the frames read and written so we can see if recording is blocked due to permissions.
Surprisingly the test semed to run OK after this patch.
Fixes #2201
> OboeTester - prevent null crash with automation

- apps/OboeTester/app/src/main/cpp/analyzer/BaseSineAnalyzer.h
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AutomatedGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java
Delete old files when the test starts.
This will help us compare passing vs failing signals.
> OboeTester: save all WAV files in Data Paths test

- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/IntentBasedTestSupport.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestAudioActivity.java
- apps/OboeTester/app/src/main/res/layout/stream_config.xml
- apps/OboeTester/docs/AutomatedTesting.md
Internal bug b/416137819
This new option will help automation test scenarios where audioserver crashed during an output stream playback
> OboeTester: Add restart_if_closed param to intents

- include/oboe/FullDuplexStream.h
Fix duplicate calls to `getOutputStream()->requestStop()`, resulting in never calling `getInputStream()->requestStop()`
Issue introduced in [this commit](https://github.com/google/oboe/commit/fae46d4c39a1918c5402cd40b84ef2cff671ff75#diff-93cf3a2be2c05a63390de19b8dc5b4104f4a3ad75d654982588d69d9b32a795a)
> Input stream not stopped in FullDuplexStream::stop

- apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTest.h
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioWorkloadTestActivity.java
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioWorkloadTestRunnerActivity.java
Workload tests leave the stream open even when the activity is closed. This PR fixes that
> Workload Tests: Close the audio stream when the activity is closed

- apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTest.h
We should protect mCallbackStatistics with a mutex. The rest of the variables already are atomic
> Fix mCallbackStatistics race condition in AudioWorkloadTest.h

- apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTest.h
- apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTestRunner.h
- apps/OboeTester/app/src/main/cpp/jni-bridge.cpp
This change several changes to make AudioWorkloadTest run better and have less crashes.
1. SynthWorkload is now created with an unique_ptr to reduce the number of crashes as SynthWorkload uses new on an array.
2. IsRunning is set to false when the stream is close/stopped.
3. Added more checks in open and start to make sure the system is in the right place when the functions are called.
4. We added waitForStateChange for stop to make sure that the system indeeds stops.
5. LOGE is used instead of std::cerr to not have blocking logs.
Fixes #2258
> OboeTester: optimize AudioWorkloadTest.h

- apps/OboeTester/app/src/main/cpp/TestColdStartLatency.cpp
- apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestColdStartLatencyActivity.java
Fixes b/440110746
For example, when you start cold start latency with input, no MMAP but exclusive set, the stream crashes. We should send a toast instead
> OboeTester: Don't crash cold start latency for invalid paths
